### ISSUE TITLE
Wine-staging-esync builds for Playonlinux

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [Kron4ek/Wine-Builds#1]
I am so thrilled about your builds, because it can be used with Playonlinux. Could you please join this discussion >>> https://github.com/PhoenicisOrg/phoenicis-winebuild/issues/73

**Comment by ahmed-elsayed2017** [comment]
I am sorry to bother you.

**Comment by Kron4ek** [comment]
Well, yes, you can use these builds with PlayOnLinux (and without it too, of course). But as the PlayOnLinux (Phoenicis) compiles their own builds, a proper solution for them is to add Hook for applying Esync patches.

**Comment by Kron4ek** [comment]
> I am sorry to bother you.

No problem. I joined the discussion from your link.

**Comment by ahmed-elsayed2017** [comment]
Ok, thanks.
