### ISSUE TITLE
Question about the latest wine 5.0

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [Kron4ek/Wine-Builds#10]
Did any of proton patches that you add manually to improved-wine builds has been added to the latest wine 5.0?

I am asking this question, because the announcement of the latest wine introduced new features that include enhancements for input devices, and fullscreen applications.

**Comment by Kron4ek** [comment]
As far as i know, no, they have not been added to the upstream (vanilla) Wine yet.

**Comment by ahmed-elsayed2017** [comment]
They will probably add them sooner or later. I don't know. Anyway, please tell me when that happens.
