### ISSUE TITLE
Wine c++ Runtime Library error R6025

### ISSUE THREAD

**Issue by dafidzparkerz** [Kron4ek/Wine-Builds#101]
I have issue with some games made with nvidia pysics.
Like Deadpool, mirrors edge and others.

I installed all vcredist but not work.
Try to install dotnet 3.5 but wine cannot install it. 
It's to hard to install dotnet 3.5 . Try install dotnet 3.5 on winetricks but error at installing.

I hope u can build wine with include dotnet 3.5
This error I can't fix it.
Maybe u know how to fix it. Thanks

**Comment by Kron4ek** [comment]
Wine already has a replacement for the proprietary .Net Framework called Mono, not all games work with it though. 

Also, not sure about Deadpool, but Mirror's Edge does not require dotnet, you only need to install PhysX and it should work:
```
$ winetricks physx
```

**Comment by dafidzparkerz** [comment]
But I always get error r6025

I install physx on winetricks but not work

**Comment by Kron4ek** [comment]
Well, Mirror's Edge works without issues for me with my wine-8.9-staging-amd64 build, and the only thing i installed is physx. I don't know why you get error r6025.
