### ISSUE TITLE
Proton latest gamepad not detect as xinput

### ISSUE THREAD

**Issue by dafidzparkerz** [Kron4ek/Wine-Builds#102]
Hello sir 

I have report. When I use gamepad it's detect as dinput not xinput. Idk why. And just detect on ds4 controller

Can u fix this for gamepad support.
The gamepad just detect only ds4 controller. Other gamepad cannot detect like ipega on wine.

I use xinput.dll from winetricks but not work

Thank you sir

**Comment by Kron4ek** [comment]
> Can u fix this for gamepad support.

No idea how to fix this.
