### ISSUE TITLE
Upgrade to cmake 3.26.4 and CROSSCC environments

### ISSUE THREAD

**Issue by rboxeur** [Kron4ek/Wine-Builds#103]
Hello my friend,
I hope you are fine. As you know my own personal chroots are based on your chroots.

**Cmake**

Just in case you meet an issue regarding cmake being outdated then below are the instructions to update it to a fresh version
I met this issue while trying to install spirv-headers from its github repository. Putting instructions here just in case you meet this issue when refreshing stable spirv-header package in the future ;)

```
wget https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4.tar.gz
tar xvzf cmake-3.26.4.tar.gz 
cd cmake-3.26.4
./bootstrap --prefix=/usr --parallel=`nproc` && make -j`nproc` && make install
```
/usr is required as prefix to point to the same prefix as the default one. Put something else if needed. I did it and it did not break my chroots. 

**CROSSCC environments**
Furthermore all  CROSSCC environment were removed from Wine 8.X. I don't know if Wine Team plans to put it back in code. But right know, I guess you can still comment it out or keep your code as-it-is
ccache is still usefull when building Wine -- native Linux code with gcc

Best regards,

**Comment by Kron4ek** [comment]
Hello.

Thank you for the info, i didn't know Wine no longer uses `CROSSCC`.
