### ISSUE TITLE
CROSSCC have been renamed. Please update

### ISSUE THREAD

**Issue by rboxeur** [Kron4ek/Wine-Builds#104]
Hello my friend,

Please remove CROSSCC and family. Below are the new variables to use instead

**64 bits Chroot**

```
export x86_64_CC="ccache x86_64-w64-mingw32-gcc"
export x86_64_CFLAGS=" -march=x86-64 -msse3 -mfpmath=sse -O2 -ftree-vectorize  "
export x86_64_LDFLAGS=" -Wl,-O1,--sort-common,--as-needed "
```

**32 Bits Chroot**

```
export i386_CC="ccache i686-w64-mingw32-gcc"
export i386_CFLAGS="-march=i686 -msse2 -mfpmath=sse -O2 -ftree-vectorize "
export i386_LDFLAGS=" -Wl,-O1,--sort-common,--as-needed "
```

Filled based on your needs. Please test and let me know if it works

Variables can easily found using grep in configure file. Other environment variables should be filled by Wine

That should speed up processes again

**Comment by Kron4ek** [comment]
Thanks, it works.
