### ISSUE TITLE
Can you build Wine GE

### ISSUE THREAD

**Issue by Presx2FForRespect** [Kron4ek/Wine-Builds#105]
Because this wine can run many games without much problems and can you make an explanation of how to build wine. I am a new person in this stuff

**Comment by Kron4ek** [comment]
You can download Wine-GE builds from [here](https://github.com/GloriousEggroll/wine-ge-custom/releases).

**Comment by ajay9634** [comment]
Only your build x86 works in Android exagear, I tried x86 x64 but it didn't work. So please build wine GE x86 only ,I love your build.
