### ISSUE TITLE
Please help, wine-proton don't work in Exagear .

### ISSUE THREAD

**Issue by ajay9634** [Kron4ek/Wine-Builds#106]
![IMG_20230621_080645_431.jpg](https://github.com/Kron4ek/Wine-Builds/assets/78233144/accba0c5-ca38-453e-bdcc-669278ca2b2c)

I don't know which files are missing.

**Comment by ajay9634** [comment]
It works in box4droid/box64droid

**Comment by ajay9634** [comment]
> It works with X doesnt mean it works with Y. Again, android is not supported, for now

Old proton work, tested by hugo

**Comment by Alien989** [comment]
will be nice build wine proton for exagear... thenks ajay for the initiative.. bump++

**Comment by Kron4ek** [comment]
I don't know how to make it work in Exagear, sorry.
