### ISSUE TITLE
Issues with Doom Eternal

### ISSUE THREAD

**Issue by Ahmed-E-86** [Kron4ek/Wine-Builds#11]
I tried your latest wine-improved build, and it gives me this error:
`FATAL ERROR: Please update your driver: VK_EXT_full_screen_exclusive is required.`

and I tried the latest proton build, and it gives me this error:
`FATAL ERROR: Please update your driver: VK_KHR_get_surface_capabilities2 is required`.

I tried switching from Kisak PPA to Obiaf PPA, I tried also switching from RADV to AMDVLK, and amdgpu-pro, but it makes no difference.

I tried updating `vulkan-loader` to the latest version from `Vulkan SDK PPA` using these commands:

```
wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-bionic.list http://packages.lunarg.com/vulkan/lunarg-vulkan-bionic.list
sudo apt update
sudo apt dist-upgrade
```
but `vulkan-loader` got updated to version `1.2.131.2`

I tried to build vulkan-headers, and vulkan-loader myself, but I always get multiple compilation errors when trying to build it.

I tried sed commands that you mentioned in this comment https://github.com/ValveSoftware/Proton/issues/3654#issuecomment-601840431

and I was able to reach the main menu, and start a new game, but the game freezes while loading, and it spams errors about `RAW inputs`, I don't remember the whole error line.

I had the same loading issue with `Doom 2016`, and I fixed back then by switching from Vulkan to OpenGL, but I was able to run `Life is Strange 2` (native), and `Wolfenstein II: The New Colossus` on the same machine.

I don't think that this issues is related to your wine builds, I am just hoping that you can help me with this issue.

**System specification:**

CPU: Intel Core I5 4200M
GPU: AMD HD Radeon 8750M
OS: Kubuntu 19.10
Kernel: 5.4.28-xanmod1

**Comment by CatalinPuscoci** [comment]
I got it to launch using vulkan-loader 1.2.135, get it from here https://github.com/KhronosGroup/Vulkan-Loader/releases

**Comment by Kron4ek** [comment]
> FATAL ERROR: Please update your driver: VK_EXT_full_screen_exclusive is required.
> FATAL ERROR: Please update your driver: VK_KHR_get_surface_capabilities2 is required

You get these errors due to old Vulkan-Loader version, version 1.2.135 is required.

**Comment by Ahmed-E-86** [comment]
I was able to build, and install the latest vulkan-loader by downloading the latest release itself instead of using `git clone https://github.com/KhronosGroup/Vulkan-Loader.git`

I will see if the game is going to run fine now after doing that.

**Comment by Kron4ek** [comment]
> one more question, do I need to use Obiaf PPA, or Kisak PPA works fine with this game?

Both should work fine, but Oibaf may give you better performance as it contains the latest git builds. However, keep in mind that git builds may contain some serious bugs or regressions.

By the way, the game uses almost 3 GB of VRAM even on lowest graphics settings (at least it did when i tested it), and it works pretty bad on GPUs with less than 3 GB of VRAM.

**Comment by Ahmed-E-86** [comment]
After installing the latest vulkan-loader, I can go to the menu, but after starting new game, it stops at 54% forever, and keeps spamming this error message:

![Screenshot_20200327_201720](https://user-images.githubusercontent.com/29783425/77787767-c7d8b800-7068-11ea-8953-071871d0903e.png)

**Comment by Kron4ek** [comment]
Is this with AMDVLK or with RADV? Also try Proton.

> but I was able to run games in the past that required more VRAM than I have with no issues.

That hurts performance a lot.  I can't say how much it hurts Doom Eternal, but, for example, in Sekiro: Shadows Die Twice performance becomes 2x-3x lower when run out of VRAM (at least for me).

**Comment by Ahmed-E-86** [comment]
Proton still gives me the same error:
`FATAL ERROR: Please update your driver: VK_KHR_get_surface_capabilities2 is required.`

I use `AMDVLK`, because I use `Kisak PPA` which still doesn't has the fix for the game. I will try Obiaf PPA to be able to use RADV instead of AMDVLK to see if there will be any performance difference, but my main issue is that game doesn't load at all, because of RawInput errors that appears in the terminal.

Is there any fix for RawInput errors that prevents the game from loading?

**Comment by Kron4ek** [comment]
> Proton still gives me the same error:
> FATAL ERROR: Please update your driver: VK_KHR_get_surface_capabilities2 is required.

That's strange, the game works for me with Proton.

> Is there any fix for RawInput errors that prevents the game from loading?

I don't think the RawInput fixme errors is the problem here, fixmes usually don't affect games significantly. I'm downloading the game again to check if i have the same errors.

**Comment by Ahmed-E-86** [comment]
I tried Obiaf PPA, but it gives me this error when I use RADV:
`FATAL ERROR: Please update your driver: VK_KHR_8bit_storage is required.`

**Comment by Kron4ek** [comment]
I downloaded the game again, i get the same RawInput errors (not many of them though, just several lines) both with my Proton and Improved build, but the game loads and works fine.

> I tried Obiaf PPA, but it gives me this error when I use RADV:
> FATAL ERROR: Please update your driver: VK_KHR_8bit_storage is required.

Hmm, the git builds should definitely contain the fix for this. Don't you have ACO enabled? I get the same error with ACO.

**Comment by Ahmed-E-86** [comment]
I was able to run the game using AMDVLK after lowering the resolution, but it crashes after cutscenes, and it doesn't run at all on Windows even after installing the latest GPU drivers. I gave up.

Thanks for trying to help me.

**Comment by Ahmed-E-86** [comment]
There is a new Mesa update that fixed the game. The game works now with LLVM, but it is noticeably slower than AMDVLK, but it doesn't crash like what happens with AMDVLK.

ACO doesn't work with the game at the moment, but it will work soon, and it may work better than LLVM.
