### ISSUE TITLE
DirectX Error (Shared Mono Install)

### ISSUE THREAD

**Issue by liberodark** [Kron4ek/Wine-Builds#111]
Hi,

Have see new issue on Proton 8.0-3 (But have no issue on steam with proton)
Fail to install DXSETUP.exe

[DirectX.log](https://github.com/Kron4ek/Wine-Builds/files/12560595/DirectX.log)
[DXError.log](https://github.com/Kron4ek/Wine-Builds/files/12560597/DXError.log)
Have try some tests is fail to install.
Proton Experimental 8.0
Proton 8.0-3
Proton 8.0-2

Link of directx from steam : 
https://uptobox.com/coxvjezmci54

Best Regards

**Comment by Kron4ek** [comment]
Hi, you can install DirectX libraries via winetricks.

**Comment by liberodark** [comment]
I think that work.

**Comment by Kron4ek** [comment]
Is there a reason why you need to use dxsetup.exe? I mean you can install DX libraries (like d3dx9, d3dcompiler, xact...) via `winetricks` or you can extract .cab files with `cabextract` and get all the dlls that dxsetup.exe installs.

**Comment by liberodark** [comment]
Because that's how I usually do and steam also does via the /silent option.
I know winetricks uses cabextract to do the installation.


```
helper_d3dx9_xx()
{
    dllname=d3dx9_$1

    helper_directx_Jun2010

    # Even kinder, less invasive directx - only extract and override d3dx9_xx.dll
    w_try_cabextract -d "${W_TMP}" -L -F "*${dllname}*x86*" "${W_CACHE}"/directx9/${DIRECTX_NAME}

    for x in "${W_TMP}"/*.cab; do
        w_try_cabextract -d "${W_SYSTEM32_DLLS}" -L -F "${dllname}.dll" "${x}"
    done

    if test "${W_ARCH}" = "win64"; then
        w_try_cabextract -d "${W_TMP}" -L -F "*${dllname}*x64*" "${W_CACHE}"/directx9/${DIRECTX_NAME}

        for x in "${W_TMP}"/*x64.cab; do
            w_try_cabextract -d "${W_SYSTEM64_DLLS}" -L -F "${dllname}.dll" "${x}"
        done
    fi

    w_override_dlls native "${dllname}"
}
```

**Comment by Kron4ek** [comment]
Well, anyway, i don't know why this issue happens and how to fix it.

**Comment by liberodark** [comment]
I understand if you have time to look I'm willing.
You have a very good level on wine and would surely be able to see perhaps something that I missed.

For the environment a Manjaro Stable (Up to date) + wine_launch_wrapper_v1.3.10 +  Proton 8.0-3 + Mono 7.4.1
PS : Witch native wine version that work...

**Comment by Kron4ek** [comment]
I investigated and figured out that the installer works without issues after installing wine-mono (i tried version 8.0.1).

**Comment by liberodark** [comment]
Yes have see that if install directly [wine-mono](https://dl.winehq.org/wine/wine-mono/7.4.0/wine-mono-7.4.0-x86.msi) that work.
But normally we don't need to do that.
If you install wine-mono in `wine/share/wine/mono` but actually that not work.

**Comment by Kron4ek** [comment]
The lack of Mono in my builds is not an issue though, i don't add it because it can be easily installed in other ways.
