### ISSUE TITLE
Wine/Proton builds with musl libc instead of glibc

### ISSUE THREAD

**Issue by varbhat** [Kron4ek/Wine-Builds#112]
I was thinking whether wine/proton can be built upon musl libc instead of glibc. Availability of wine in voidlinux actually reassures that it's indeed possible to do so. 

Disadvantage of glibc is that it's ABI stability doesn't have good record and breaks softwares many times. i think that musl can help resolve this

**Comment by Kron4ek** [comment]
> Disadvantage of glibc is that it's ABI stability doesn't have good record and breaks softwares many times.

Well, that's true that it breaks some software sometimes (recent example is the Easy AntiCheat breakage with glibc 2.36; also Electron apps with glibc 2.34), but i don't remember any glibc-related breakages affecting Wine. So i don't think it makes much sense to compile Wine with musl, but maybe i'll change my mind in the future.

**Comment by varbhat** [comment]
@Kron4ek I didn't ask you to replace glibc with musl but instead provide additional builds based upon musl.

**Comment by Kron4ek** [comment]
This does not change anything, i don't see the point in providing them given that glibc builds work fine. I understand that musl-based distros can not run glibc-compiled builds, but they can run them in a container.
