### ISSUE TITLE
Wine with wow64 (--enable-archs=i386,x86_64) build?

### ISSUE THREAD

**Issue by Kawasaki443** [Kron4ek/Wine-Builds#113]
All modules in wine have been changed into PE format, so could you build a wine package with "--enable-archs=i386,x86_64" flag to support wow64 without any lib32?

**Comment by Kron4ek** [comment]
Such builds are already available, just on the release page. You can download them from [here](https://github.com/Kron4ek/Wine-Builds/actions/workflows/wine-exp-wow64.yml).
