### ISSUE TITLE
Gcc 11.4 are avaible on chroot. I could offer my own mingw-w64 binaires if you want

### ISSUE THREAD

**Issue by rboxeur** [Kron4ek/Wine-Builds#116]
Hi Kron4ek,

Right now if you want to upgrade from gcc-9 or gcc-10 to gcc-11 then it could be done using apt tools.
Then your chroots will point to gcc-11

I am currently using that version on my both chroots
I built my own MinGW-w644 built againt gcc-11.4.1 and mingw-w64-git from yesterday.
You can download them here

http://techer.pascal.free.fr/download/Red-Rose-Gcc-11.4.1-MinGW-w64-Posix-v11.0.0.r543.g883cc25d7-git.tar.xz

Here is the shell script I used 

http://techer.pascal.free.fr/scripts/build-mingw-w64-toolchain-generic.sh

**All binairies are built statically and could be used on both chroots - almost portable**

If you are interested then 

on your personal machine

```
wget http://techer.pascal.free.fr/download/Red-Rose-Gcc-11.4.1-MinGW-w64-Posix-v11.0.0.r543.g883cc25d7-git.tar.xz
tar xvJf Red-Rose-Gcc-11.4.1-MinGW-w64-Posix-v11.0.0.r543.g883cc25d7-git.tar.xz -C /opt/
```

on both chroots create that folder and then mount it

```
mkdir -pv /path/to/your/chroot/opt/Red-Rose-Gcc-11.4.1-MinGW-w64-Posix-v11.0.0.r543.g883cc25d7-git

mount /opt/Red-Rose-Gcc-11.4.1-MinGW-w64-Posix-v11.0.0.r543.g883cc25d7-git /path/to/your/chroot/opt/Red-Rose-Gcc-11.4.1-MinGW-w64-Posix-v11.0.0.r543.g883cc25d7-git
```

Put /opt/Red-Rose-Gcc-11.4.1-MinGW-w64-Posix-v11.0.0.r543.g883cc25d7-git/bin/ at the beginning PATH environment variable for each chroot

That's it!!!

Now you have a new Gcc11.4 from original packages and a portable MinGW-w64-gcc

**Comment by Kron4ek** [comment]
Hi, rboxeur, thank you for the information. Currently i'm ok with older gcc and mingw versions, but your information may be useful in the future if Wine requires newer gcc/mingw versions for compilation.
