### ISSUE TITLE
A request for wine-improved builds

### ISSUE THREAD

**Issue by Ahmed-E-86** [Kron4ek/Wine-Builds#12]
Could you please add this patch to your wine-builds? >>> https://github.com/Frogging-Family/community-patches/blob/master/wine-tkg-git/Do_not_fail_if_LDR_MODULE.Flags_is_modified.mypatch

It helps to run some games that normally don't run on wine, and building custom wine build on Ubuntu is so hard, because dependencies are so problematic, and hard to resolve.

If you don't like adding this patch to your improved-wine build just close this issue, and thank in advance whatever you decided to do it or not.

**Comment by Kron4ek** [comment]
The patch seems harmless, i will add it in the next release.

**Comment by Ahmed-E-86** [comment]
Many thanks.

One more question if you don't mind: How can I use your build script to build my own builds with whatever patches I want on Kubuntu 19.10?

**Comment by Kron4ek** [comment]
> How can I use your build script to build my own builds with whatever patches I want on Kubuntu 19.10?

First, install these packages: debootstrap git wget autoconf perl

Second, edit MAINDIR variable in the create_ubuntu_chroots.sh and build_wine.sh, set it to the desired existing location. You can also edit other variables (for example, CFLAGS) if you want, but that's optional.

Run the create_ubuntu_chroots.sh with root rights, it will create two Ubuntu chroots, which then will be used by build_wine.sh script for compilation.

    sudo ./create_ubuntu_chroots.sh

Then run build_wine.sh with root rights. For example, this will build the latest (5.5) improved build:

    sudo ./build_wine.sh latest improved

And just wait, you will get three tar.xz archives (amd64, amd64-nomultilib and x86) when the compilation is done.

To add or remove patches edit the build_wine.sh script.

p.s. I've added the patch that you requested to the script, so the command above will compile the build with the patch applied.

**Comment by Ahmed-E-86** [comment]
I did what you said, and I was able to build it myself. It was a way longer than what I expected, but I feel the work behind it. I appreciate your help. Thanks.

**Comment by Ahmed-E-86** [comment]
The patch has been updated, and its name has been changed from `Do_not_fail_if_LDR_MODULE.Flags_is_modified.mypatch` to `Use_a_cached_version_of_LDR_MODULE_flags_for_InitDLL.mypatch`

Please update your `build_wine.sh`

**Comment by Kron4ek** [comment]
The patch is now included in Staging.

https://github.com/wine-staging/wine-staging/commit/776306026af908838b408ce86687328f1e574d42

**Comment by Ahmed-E-86** [comment]
> The patch is now included in Staging.
> 
> [wine-staging/wine-staging@7763060](https://github.com/wine-staging/wine-staging/commit/776306026af908838b408ce86687328f1e574d42)

Thanks, good to know.
