### ISSUE TITLE
 wine-9.0-staging-amd64 error when creating / updating prefix

### ISSUE THREAD

**Issue by keybreak** [Kron4ek/Wine-Builds#120]
Not sure if it's upstream or caused by build, but here it is:

```bash
wine: Call from 00006FFFFFC13557 to unimplemented function ole32.dll.CoInitialize, aborting
wine: Unimplemented function ole32.dll.CoInitialize called at address 00006FFFFFC13557 (thread 0140), starting debugger...
wine: Call from 00006FFFFFC13557 to unimplemented function ole32.dll.CoRegisterInitializeSpy, aborting
wine: Call from 00006FFFFFC13557 to unimplemented function ole32.dll.CoRegisterInitializeSpy, aborting
```

It seems to still create prefix, but probably something is f$cked, otherwise there won't be an error during the process  :laughing:

**Comment by Kron4ek** [comment]
Works fine on my system, i don't get these errors.

**Comment by keybreak** [comment]
Interesting...I was trying it on Manjaro Stable so far.

**Comment by keybreak** [comment]
Tried on pure Arch right now - everything is fine. Probably yet another Manjaro downstream screwup. :unamused: 
Sorry for false alarm!
