### ISSUE TITLE
Are WoW64 builds planned in the future?

### ISSUE THREAD

**Issue by GabiAle97** [Kron4ek/Wine-Builds#121]
Just like the normal ones on the "Release" section, is there a chance to have WoW64 version of Wine builds?

**Comment by Kron4ek** [comment]
Yes, i plan to add them in the future.

**Comment by DocMAX** [comment]
+1, please release them like the normal ones

**Comment by rossowl** [comment]
+1 for x86_64 builds, my brand new system is lib32 and X11 free. Many thanks

**Comment by kwankiu** [comment]
+1, we really need this for Arch Linux ARM

**Comment by liberodark** [comment]
Yes that strange on release : https://github.com/Kron4ek/Wine-Builds/releases/tag/proton-8.0-5 that work great with `wine-proton-8.0-5-amd64.tar.xz` i can run games in wow64 but with last release now that not work.

**Comment by mio-19** [comment]
> Yes that strange on release : https://github.com/Kron4ek/Wine-Builds/releases/tag/proton-8.0-5 that work great with `wine-proton-8.0-5-amd64.tar.xz` i can run games in wow64 but with last release now that not work.

Is this build wow64?

**Comment by Kron4ek** [comment]
Added.
