### ISSUE TITLE
[New build request] Wine (mainline/staging) with winesync

### ISSUE THREAD

**Issue by bunkbail** [Kron4ek/Wine-Builds#122]
Winesync (https://github.com/Frogging-Family/wine-tkg-git/issues/936) is giving a decent fps boost in some titles for me, so it would be great if you can provide some builds (don't have to be frequent updates) with the functionality included. Proton-cachyos builds works well for me but for some reason it breaks network connectivity on steam (via wine) for me. Steam in wine is very important to me and all of your wine and proton builds are working fine for me, so please consider making the build available.

**Comment by Kron4ek** [comment]
I'll think about it.

**Comment by Etaash-mathamsetty** [comment]
any updates on this since ntsync is now part of linux-zen and is in the process of being upstreamed into the linux kernel?

**Comment by Kron4ek** [comment]
[Added](https://github.com/Kron4ek/Wine-Builds/actions/runs/9052765657) ntsync builds to Actions. Currently they are half broken though, only 64-bit applications work with ntsync enabled, don't know if i did something wrong or it's just a bug.

For 32-bit applications ntsync has to be disabled, Wine can't event create a 32-bit prefix if it's enabled.
```
$ wine-9.8-staging-tkg-ntsync-amd64/bin/wine64 winecfg
wine: using fast synchronization.
$ wine-9.8-staging-tkg-ntsync-amd64/bin/wine winecfg
wine: created the configuration directory
wine: using fast synchronization.
wine: could not load kernel32.dll, status c0000135
$ WINE_DISABLE_FAST_SYNC=1 wine-9.8-staging-tkg-ntsync-amd64/bin/wine winecfg
wine: created the configuration directory
ntsync is explicitly disabled.
wine: configuration in has been updated.
```

**Comment by bunkbail** [comment]
yeah i can confirm this. i've been building wine-tkg with winesync/ntsync for awhile, 32-bit games aren't launching.
