### ISSUE TITLE
[New patch request] HAGS support patch

### ISSUE THREAD

**Issue by oscarbg** [Kron4ek/Wine-Builds#125]
Hi,
If not late for next release can consider adding:

https://gist.github.com/Saancreed/0aa3f4188846146698f5da3dfa0dfcbd#file-hags-0002-patch

 It’s a small patch.. applies cleanly.. 
and functionality only conditionally enabled via setting WINEHAGS=1 env variable..

In short allows testing fsr3 dlss3 mod on dlss3 frame gen games and also own nvidia frame gen dlssg games even they render black..

For more info see: ( note patch 001 is not needed since integrated in some way in wine 9.x)
https://github.com/Nukem9/dlssg-to-fsr3/issues/93#issuecomment-1863639854

**Comment by Kron4ek** [comment]
Added to staging-tkg-9.4.

**Comment by oscarbg** [comment]
thanks!

**Comment by oscarbg** [comment]
patch needs minor change for wine 9.5+:


correct 002 patch for 9.5+:

```
diff --git a/dlls/win32u/d3dkmt.c b/dlls/win32u/d3dkmdiff --git a/dlls/win32u/d3dkmt.c b/dlls/win32u/d3dkmt.c
index f4d695ac0cb..c489601e147 100644
--- a/dlls/win32u/d3dkmt.c
+++ b/dlls/win32u/d3dkmt.c
@@ -223,15 +223,48 @@ NTSTATUS WINAPI NtGdiDdDDIDestroyDevice( const D3DKMT_DESTROYDEVICE *desc )
     return STATUS_SUCCESS;
 }
 
+static BOOL check_hags_enabled( void )
+{
+    const char *winehags = getenv( "WINEHAGS" );
+    return winehags && *winehags != '0';
+}
+
 /******************************************************************************
  *           NtGdiDdDDIQueryAdapterInfo    (win32u.@)
  */
 NTSTATUS WINAPI NtGdiDdDDIQueryAdapterInfo( D3DKMT_QUERYADAPTERINFO *desc )
 {
+    D3DKMT_WDDM_2_7_CAPS *d3dkmt_wddm_2_7_caps;
+
     if (!desc) return STATUS_INVALID_PARAMETER;
 
-    FIXME( "desc %p, type %d stub\n", desc, desc->Type );
-    return STATUS_NOT_IMPLEMENTED;
+    TRACE("desc %p, type %d\n", desc, desc->Type);
+
+    switch (desc->Type)
+    {
+        case KMTQAITYPE_WDDM_2_7_CAPS:
+            if (!desc->pPrivateDriverData || desc->PrivateDriverDataSize != sizeof(D3DKMT_WDDM_2_7_CAPS))
+                return STATUS_INVALID_PARAMETER;
+
+            d3dkmt_wddm_2_7_caps = desc->pPrivateDriverData;
+            d3dkmt_wddm_2_7_caps->HwSchSupported = 1;
+            d3dkmt_wddm_2_7_caps->HwSchEnabled = 0;
+            d3dkmt_wddm_2_7_caps->HwSchEnabledByDefault = 0;
+            d3dkmt_wddm_2_7_caps->IndependentVidPnVSyncControl = 0;
+
+            if (check_hags_enabled())
+            {
+                d3dkmt_wddm_2_7_caps->HwSchEnabled = 1;
+                d3dkmt_wddm_2_7_caps->HwSchEnabledByDefault = 1;
+            }
+            break;
+
+        default:
+            FIXME("type %d not supported\n", desc->Type);
+            return STATUS_NOT_IMPLEMENTED;
+    }
+
+    return STATUS_SUCCESS;
 }
 
 /******************************************************************************
diff --git a/include/ddk/d3dkmthk.h b/include/ddk/d3dkmthk.h
index 918a4ad..4b2c5a7 100644
--- a/include/ddk/d3dkmthk.h
+++ b/include/ddk/d3dkmthk.h
@@ -773,6 +773,22 @@ typedef struct _D3DKMT_ENUMADAPTERS2
   D3DKMT_ADAPTERINFO *pAdapters;
 } D3DKMT_ENUMADAPTERS2;
 
+typedef struct _D3DKMT_WDDM_2_7_CAPS
+{
+  union
+  {
+    struct
+    {
+      UINT HwSchSupported               :  1;
+      UINT HwSchEnabled                 :  1;
+      UINT HwSchEnabledByDefault        :  1;
+      UINT IndependentVidPnVSyncControl :  1;
+      UINT Reserved                     : 28;
+    };
+    UINT Value;
+  };
+} D3DKMT_WDDM_2_7_CAPS;
+
 #ifdef __cplusplus
 extern "C"
 {
t.c
index f4d695ac0cb..c489601e147 100644
--- a/dlls/win32u/d3dkmt.c
+++ b/dlls/win32u/d3dkmt.c
@@ -223,15 +223,48 @@ NTSTATUS WINAPI NtGdiDdDDIDestroyDevice( const D3DKMT_DESTROYDEVICE *desc )
     return STATUS_SUCCESS;
 }
 
+static BOOL check_hags_enabled( void )
+{
+    const char *winehags = getenv( "WINEHAGS" );
+    return winehags && *winehags != '0';
+}
+
 /******************************************************************************
  *           NtGdiDdDDIQueryAdapterInfo    (win32u.@)
  */
 NTSTATUS WINAPI NtGdiDdDDIQueryAdapterInfo( D3DKMT_QUERYADAPTERINFO *desc )
 {
+    D3DKMT_WDDM_2_7_CAPS *d3dkmt_wddm_2_7_caps;
+
     if (!desc) return STATUS_INVALID_PARAMETER;
 
-    FIXME( "desc %p, type %d stub\n", desc, desc->Type );
-    return STATUS_NOT_IMPLEMENTED;
+    TRACE("desc %p, type %d\n", desc, desc->Type);
+
+    switch (desc->Type)
+    {
+        case KMTQAITYPE_WDDM_2_7_CAPS:
+            if (!desc->pPrivateDriverData || desc->PrivateDriverDataSize != sizeof(D3DKMT_WDDM_2_7_CAPS))
+                return STATUS_INVALID_PARAMETER;
+
+            d3dkmt_wddm_2_7_caps = desc->pPrivateDriverData;
+            d3dkmt_wddm_2_7_caps->HwSchSupported = 1;
+            d3dkmt_wddm_2_7_caps->HwSchEnabled = 0;
+            d3dkmt_wddm_2_7_caps->HwSchEnabledByDefault = 0;
+            d3dkmt_wddm_2_7_caps->IndependentVidPnVSyncControl = 0;
+
+            if (check_hags_enabled())
+            {
+                d3dkmt_wddm_2_7_caps->HwSchEnabled = 1;
+                d3dkmt_wddm_2_7_caps->HwSchEnabledByDefault = 1;
+            }
+            break;
+
+        default:
+            FIXME("type %d not supported\n", desc->Type);
+            return STATUS_NOT_IMPLEMENTED;
+    }
+
+    return STATUS_SUCCESS;
 }
 
 /******************************************************************************
diff --git a/include/ddk/d3dkmthk.h b/include/ddk/d3dkmthk.h
index 918a4ad..4b2c5a7 100644
--- a/include/ddk/d3dkmthk.h
+++ b/include/ddk/d3dkmthk.h
@@ -773,6 +773,22 @@ typedef struct _D3DKMT_ENUMADAPTERS2
   D3DKMT_ADAPTERINFO *pAdapters;
 } D3DKMT_ENUMADAPTERS2;
 
+typedef struct _D3DKMT_WDDM_2_7_CAPS
+{
+  union
+  {
+    struct
+    {
+      UINT HwSchSupported               :  1;
+      UINT HwSchEnabled                 :  1;
+      UINT HwSchEnabledByDefault        :  1;
+      UINT IndependentVidPnVSyncControl :  1;
+      UINT Reserved                     : 28;
+    };
+    UINT Value;
+  };
+} D3DKMT_WDDM_2_7_CAPS;
+
 #ifdef __cplusplus
 extern "C"
 {

```

**Comment by gilvbp** [comment]
> patch needs minor change for wine 9.5+: basically changes a part of the patch from driver.c file to d3dkmt.c correct 002 patch for 9.5+:
> 
> ```
> diff --git a/dlls/win32u/d3dkmt.c b/dlls/win32u/d3dkmt.c
> index f4d695ac0cb..c489601e147 100644
> --- a/dlls/win32u/d3dkmt.c
> +++ b/dlls/win32u/d3dkmt.c
> @@ -223,15 +223,48 @@ NTSTATUS WINAPI NtGdiDdDDIDestroyDevice( const D3DKMT_DESTROYDEVICE *desc )
>      return STATUS_SUCCESS;
>  }
>  
> +static BOOL check_hags_enabled( void )
> +{
> +    const char *winehags = getenv( "WINEHAGS" );
> +    return winehags && *winehags != '0';
> +}
> +
>  /******************************************************************************
>   *           NtGdiDdDDIQueryAdapterInfo    (win32u.@)
>   */
>  NTSTATUS WINAPI NtGdiDdDDIQueryAdapterInfo( D3DKMT_QUERYADAPTERINFO *desc )
>  {
> +    D3DKMT_WDDM_2_7_CAPS *d3dkmt_wddm_2_7_caps;
> +
>      if (!desc) return STATUS_INVALID_PARAMETER;
>  
> -    FIXME( "desc %p, type %d stub\n", desc, desc->Type );
> -    return STATUS_NOT_IMPLEMENTED;
> +    TRACE("desc %p, type %d\n", desc, desc->Type);
> +
> +    switch (desc->Type)
> +    {
> +        case KMTQAITYPE_WDDM_2_7_CAPS:
> +            if (!desc->pPrivateDriverData || desc->PrivateDriverDataSize != sizeof(D3DKMT_WDDM_2_7_CAPS))
> +                return STATUS_INVALID_PARAMETER;
> +
> +            d3dkmt_wddm_2_7_caps = desc->pPrivateDriverData;
> +            d3dkmt_wddm_2_7_caps->HwSchSupported = 1;
> +            d3dkmt_wddm_2_7_caps->HwSchEnabled = 0;
> +            d3dkmt_wddm_2_7_caps->HwSchEnabledByDefault = 0;
> +            d3dkmt_wddm_2_7_caps->IndependentVidPnVSyncControl = 0;
> +
> +            if (check_hags_enabled())
> +            {
> +                d3dkmt_wddm_2_7_caps->HwSchEnabled = 1;
> +                d3dkmt_wddm_2_7_caps->HwSchEnabledByDefault = 1;
> +            }
> +            break;
> +
> +        default:
> +            FIXME("type %d not supported\n", desc->Type);
> +            return STATUS_NOT_IMPLEMENTED;
> +    }
> +
> +    return STATUS_SUCCESS;
>  }
>  
>  /******************************************************************************
> diff --git a/include/ddk/d3dkmthk.h b/include/ddk/d3dkmthk.h
> index 918a4ad..4b2c5a7 100644
> --- a/include/ddk/d3dkmthk.h
> +++ b/include/ddk/d3dkmthk.h
> @@ -773,6 +773,22 @@ typedef struct _D3DKMT_ENUMADAPTERS2
>    D3DKMT_ADAPTERINFO *pAdapters;
>  } D3DKMT_ENUMADAPTERS2;
>  
> +typedef struct _D3DKMT_WDDM_2_7_CAPS
> +{
> +  union
> +  {
> +    struct
> +    {
> +      UINT HwSchSupported               :  1;
> +      UINT HwSchEnabled                 :  1;
> +      UINT HwSchEnabledByDefault        :  1;
> +      UINT IndependentVidPnVSyncControl :  1;
> +      UINT Reserved                     : 28;
> +    };
> +    UINT Value;
> +  };
> +} D3DKMT_WDDM_2_7_CAPS;
> +
>  #ifdef __cplusplus
>  extern "C"
>  {
> ```

Thanks!

**Comment by FSKiller** [comment]
Sadly this has been removed in the 9.9 Release. Any updated patches?

**Comment by Kron4ek** [comment]
Yes, will add it in the next release.

**Comment by gilvbp** [comment]
On 10.2 is broken again

**Comment by Kron4ek** [comment]
@oscarbg Thanks.

**Comment by ofirtim** [comment]
Hello, is still included in current staging versions?
It may or may not help me fix the stubs I get with type 48 and 36, since some games require HAGS enabled for FSR3 frame generation, and it seems like the only valid option to actually fix this.

**Comment by Kron4ek** [comment]
@ofirtim Yes, it is included in my recent staging-tkg builds. I don't know if it's still useful, but at least it applies cleanly.

**Comment by ofirtim** [comment]
> @ofirtim Yes, it is included in my recent staging-tkg builds. I don't know if it's still useful, but at least it applies cleanly.

It actually will, it seems like HAGS features haven't fully been implemented yet in main Wine, Arc Raiders got FSR3 frame gen and it simply won't appear for me, seems like it'll fix the 31 + 48 stubs i get.
