### ISSUE TITLE
Missing directories when building wine-staging-9.4

### ISSUE THREAD

**Issue by MadByteDE** [Kron4ek/Wine-Builds#126]
When trying to build wine-staging-9.4, `bin` and `share` directories won't get created, resulting in a corrupted build. Using the same `build_wine.sh` to build wine 9.3 or 9.2 works just fine.

I've tried to clone the repo again, but the issue persists.

**Comment by Kron4ek** [comment]
This is an upstream bug. You need to change the value of `STAGING_ARGS` env variable inside `build_wine.sh` to `--all -W user32-rawinput-mouse` for it to compile.

https://bugs.winehq.org/show_bug.cgi?id=56410

**Comment by MadByteDE** [comment]
Thanks a lot :) :+1:
