### ISSUE TITLE
Build Help

### ISSUE THREAD

**Issue by Jacobw1oo** [Kron4ek/Wine-Builds#127]
your scripts are amazing, i dont know know how to work them well. and i need a greatly divergent build, wine ge lol 8-27 for Termux Android. it is proton based from GloriousEggroll.

First i am cross compiling for an arch Amd64 system ( processors is correct with amd64 but i have to apply termux patches on top of lol patches), i don't think this will be my main issue. i see it bootstrapped with a bubble wrap builder.

A i cant configure to build proton, second could not to transplant GloriousEggroll github. lastly the patches i have to apply are terrible (i have learned, how to get these patches working) , fix-address-space.diff, ge-8-25.patch

Please Help

**Comment by Kron4ek** [comment]
I don't know about cross-compilation, but regular compilation of custom builds can be done this way:

1. Download the source code you want to compile
2. Apply any patches to it
3. Specify the path to the source code in the `CUSTOM_SRC_PATH` environment variable in `build_wine.sh`
4. Run `build_wine.sh`

**Comment by Jacobw1oo** [comment]
thank you, great quick responses.  How to i compile a normal proton without custom source. it is a another piece to the puzzle. i am looking at GloriousEggroll Wine, it designed to compile in docker, so has no wine files, only the patches.

**Comment by Kron4ek** [comment]
The source code of GloriousEggroll builds (up to 8-26) is available [here](https://github.com/GloriousEggroll/proton-wine/tree/Proton8-26).

**Comment by Jacobw1oo** [comment]
wow, that is exactly what needed. thank you very much. i will try to glue these pieces i got together

**Comment by Jacobw1oo** [comment]
humm, which wine-staging do i need?

**Comment by Jacobw1oo** [comment]
your script design is cross compile, using a container compiler, setting all the CCcross setting, not using the native system gcc or libs. which is causing an issue with wine 9.4.

wine-staging 9.4 build fails on Debian 11, Ubuntu 20.04 and 22.04 is a know bug.

I am on arch with gcc 13, your script uses gcc 9.1.

**Comment by Kron4ek** [comment]
Wine-Staging 9.4 compilation has been fixed in 9.4.1.

**Comment by Jacobw1oo** [comment]
ooo, i will compile that after my current one.

**Comment by Jacobw1oo** [comment]
got any ides on this build_wine/wine/dlls/winex11.drv/vulkan.c:1067:6: error: conflicting types for ‘resize_vk_surfaces’

**Comment by Kron4ek** [comment]
Don't know.
