### ISSUE TITLE
Update to newer Ubuntu LTS

### ISSUE THREAD

**Issue by davidebeatrici** [Kron4ek/Wine-Builds#129]
18.04 (Bionic Beaver) has been out of support since 31 May 2023.

From https://ubuntu.com/about/release-cycle:

![](https://github.com/Kron4ek/Wine-Builds/assets/5897523/71548e49-84e5-484e-80ae-b00bcdb26379)

**Comment by Kron4ek** [comment]
I don't think updating build environment to a newer distro is worth it, Ubuntu 18.04 is sufficient for now.

**Comment by davidebeatrici** [comment]
Alright.
