### ISSUE TITLE
Why is winegstreamer disabled?

### ISSUE THREAD

**Issue by clebercasali** [Kron4ek/Wine-Builds#13]
Some games have cutscene videos, that work with vanilla wine on *Ubuntu 20.04, provided you have the required libs installed.

Ultra Street Fighter IV, for example. Videos will play with vanilla wine, provided you have the following libs installed: 
 gstreamer1.0-libav:i386
 gstreamer1.0-plugins-bad:i386
 gstreamer1.0-plugins-base:i386
 gstreamer1.0-plugins-good:i386
 gstreamer1.0-plugins-ugly:i386
 gstreamer1.0-x:i386
 libgstreamer-plugins-bad1.0-0:i386
 libgstreamer-plugins-base1.0-0:i386
 libgstreamer-plugins-good1.0-0:i386
 libgstreamer1.0-0:i386

 But videos won't play with your wine builds because winegstreamer is disabled on compilation.

**Comment by Kron4ek** [comment]
It caused issues for me in some games several years ago, i always disable it since then. Maybe i will enable in the next release.

[Here](https://drive.google.com/open?id=1zexBVL7pQM22N1GiUWMQryVqPwreTSHo) is the Staging 5.6 build with winegstreamer enabled, check it out and tell me if it plays videos fine.

**Comment by clebercasali** [comment]
It worked indeed! Thank you!

If winegstreamer causes issues with a game, you can launch the game with:
env WINEDLLOVERRIDES="winegstreamer=" wine mygame.exe

So winegstreamer will be disabled.

**Comment by clebercasali** [comment]
![screen](https://user-images.githubusercontent.com/13246236/79379731-b717b580-7f35-11ea-8fed-19652235deef.jpg)

**Comment by Kron4ek** [comment]
> It worked indeed! Thank you!

Good. I will compile the next release with winegstreamer.
