### ISSUE TITLE
Wow64 wine sound issue

### ISSUE THREAD

**Issue by ajay9634** [Kron4ek/Wine-Builds#130]
Hello I tested wow64 wine from here

https://github.com/Kron4ek/Wine-Builds/actions/workflows/wine-exp-wow64.yml

But I am getting sound error in 32 bit games. 16 bit sound isn't supported in your wine.

I tested cod2 and many games in winlator with your wow64 wine.
This is the error. Please fix this.

![Screenshot_2024-04-28-08-41-05-107_com winlator](https://github.com/Kron4ek/Wine-Builds/assets/78233144/2e18d49f-7c98-4e0e-9a49-e83458d48a03)

I tested other wow64 wine from afei and no sound error.

**Comment by Kron4ek** [comment]
I can't reproduce the issue on my system, it's probably related to emulation.

**Comment by Kron4ek** [comment]
Try [this](https://github.com/Kron4ek/Wine-Builds/actions/runs/8949057552) build.

**Comment by Kron4ek** [comment]
You can convert any regular amd64 build into wow64 by removing `wine` and `wine-preloader` binaries and copying `wine64` into `wine`.
```
$ cd wine-8.18-amd64/bin
$ rm wine wine-preloader
$ cp wine64 wine
```
