### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by ghost** [Kron4ek/Wine-Builds#131]
Had a solid go at this on debian raspberry pi5

but I could do with a guide.

sorry if this doesn't count for  a issue there is just next to no installation tutorials for this

thanks for your time

**Comment by Kron4ek** [comment]
Hi. Sorry, I'm not an expert on x86 emulation on ARM platforms.

**Comment by Kron4ek** [comment]
Simple instructions are already [here](https://github.com/Kron4ek/Wine-Builds?tab=readme-ov-file#how-to-use).

**Comment by lu1lu2i** [comment]
I meant step by step it would be better if you actually put the instructions on seperate area for people to read instead of crammed in

**Comment by Kron4ek** [comment]
I don't think a step by step guide is needed.
