### ISSUE TITLE
MinGW-w64 v12.0.0 for Ubuntu 18.04

### ISSUE THREAD

**Issue by rboxeur** [Kron4ek/Wine-Builds#133]
Hi Kron4ek,

MinGW-w64 v12.0.0 was released on 29-May-2024
 Since Gcc-11.4.0 is available as package for Ubuntu 18.04 then I built binaries for MinGw-w64-v12.0.0 with Posix and UCRT

You can upgrade gcc-11.4.0 on Ubuntu 18.04 to point to it instead of your current gcc version

You can download my own built binaires here

**Builds are static so you can mount them on machine where your chroots are located -- based on Canadian Cross Compilation**

```
wget http://techer.pascal.free.fr/Red-Rose_MinGW-w64-Toolchain/Red-Rose-MinGW-w64-Posix-Urct-v12.0.0.r0.g819a6ec2e-Gcc-11.4.1.tar.xz

tar xvJf Red-Rose-MinGW-w64-Posix-Urct-v12.0.0.r0.g819a6ec2e-Gcc-11.4.1.tar.xz -C /

```
then where you call bwrap updating PATH

from

`--setenv PATH "/bin:/sbin:/usr/bin:/usr/sbin" `

to 

`--setenv PATH "/opt/Red-Rose-MinGW-w64-Posix-Urct-v12.0.0.r0.g819a6ec2e-Gcc-11.4.1/bin:/bin:/sbin:/usr/bin:/usr/sbin" `

and to add this line

`--bind-try /opt/Red-Rose-MinGW-w64-Posix-Urct-v12.0.0.r0.g819a6ec2e-Gcc-11.4.1 /opt/Red-Rose-MinGW-w64-Posix-Urct-v12.0.0.r0.g819a6ec2e-Gcc-11.4.1`

You need to perform `mkdir /opt/chroots/opt/Red-Rose-MinGW-w64-Posix-Urct-v12.0.0.r0.g819a6ec2e-Gcc-11.4.1` inside your respective chroot location so this point could be mounted and could be used based on your first shell script content.

Here is the shell script I used to build those binaires

http://techer.pascal.free.fr/Red-Rose_MinGW-w64-Toolchain/build-mingw-w64-toolchain-v12.0.0-generic.sh

- bin-utils-2.38 with patches and CVS and a few backports
-  gcc 11.4.1 with patches, CVS and a few backports
-  mpfr 4.2.1
- gmp 6.3.0
- isl 0.26
- mpc 1.3.1

Give it a try and then let me know. That should make your incoming Wine builds more accurate and up-to-date.
Hope it helps,
Regards

**Comment by Kron4ek** [comment]
Thanks, maybe will try it later.

**Comment by Kron4ek** [comment]
Thanks again, your MinGW works good, i will use it to compile my builds.
