### ISSUE TITLE
Esync in vanilla 

### ISSUE THREAD

**Issue by ajay9634** [Kron4ek/Wine-Builds#134]
Hi,
I am not an expert in modding wine or building wine.
Is there any way to work esync in vanilla wine.
I want wine 8.2 vanilla with esync.
Since winlator doesn't support staging or tkg.

**Comment by Kron4ek** [comment]
Hi. It's possible by recompiling Wine and adding the Esync patchset.

**Comment by Kron4ek** [comment]
> Is there any possibility by replacing some dlls or libs?

I think doing this will break Wine.
