### ISSUE TITLE
Wine 8.21 wow64

### ISSUE THREAD

**Issue by klark231** [Kron4ek/Wine-Builds#135]
Please can you release a Wow64 build of Wine 8.21. Dinput8 on wine 9.x is bugged it will work for a few minutes then will stop working and get stucked. on wine 8.x its good. All ypur wow64 build of wine 8.x is expired

**Comment by Kron4ek** [comment]
Hi. You can convert any regular amd64 build into wow64 by removing `wine` and `wine-preloader` binaries and copying `wine64` into `wine`.
```
$ cd wine-8.21-amd64/bin
$ rm wine wine-preloader
$ cp wine64 wine
```

**Comment by klark231** [comment]
did not work
