### ISSUE TITLE
[Question] NTsync

### ISSUE THREAD

**Issue by Hexality** [Kron4ek/Wine-Builds#137]
does staging tkg builds have _use_ntsync patch enabled already?

**Comment by Kron4ek** [comment]
On the releases page they does not, but there are ntsync builds available [here](https://github.com/Kron4ek/Wine-Builds/actions/workflows/wine-ntsync.yml).

**Comment by Hexality** [comment]
okay, thanks.

Em ter., 16 de jul. de 2024 às 15:07, Kron4ek ***@***.***>
escreveu:
