### ISSUE TITLE
Wine32 - Can't exec wineserver

### ISSUE THREAD

**Issue by anonimo82** [Kron4ek/Wine-Builds#138]
Hello everyone.
On running Wine32, I always get this error: 
![Screenshot_2024-07-19_22-31-51](https://github.com/user-attachments/assets/64f6c79b-2dba-4155-ba6c-befcf7f9f820)
Wine64 runs perfectly.

Why am I getting this?
It's been a while, because I also had issues with sume major versions down (2 or 3 major before).
I were following IvonBlog guide to VirGL, Box86+Wine and Proot with Termux guides.

Thanks in advance for any help. Regards, have a nice day.
^.^

**Comment by calculatortamer** [comment]
i have the same issue with box86 v0.3.7 fcbebfa8, it said "wine: chdir to /tmp/.wine-1000/server-b301-669acbb8 : No such file or directory"

i reverted to lastest stable box86 v0.3.6 release and it seems to work better

**Comment by anonimo82** [comment]
I can't revert because I'm using the .deb from a repo.
Any other solution?
