### ISSUE TITLE
Wine pipe_nowait patch

### ISSUE THREAD

**Issue by qurious-pixel** [Kron4ek/Wine-Builds#14]
Rockstar Games Launcher fails to update

Can you add the pipe_nowait patch from Proton?
It is necessary for Rockstar Games Launcher.

https://github.com/wine-mirror/wine/commit/abb1ce10870d12ce5752abce81fd50bddf236180

https://bugs.winehq.org/show_bug.cgi?id=47843

**Comment by Kron4ek** [comment]
Sure, i suppose the patch is harmless since it's included in Proton.

I will upload the test build for you a little later.

**Comment by Kron4ek** [comment]
[Here](https://drive.google.com/open?id=1-QR0S6GSRBuTTeO7N52q_uQyfaP8rTIq) is the Staging-Improved 5.6 build with the two additional patches for RG Launcher, tell me if it fixes issues with Rockstar Games Launcher.

**Comment by qurious-pixel** [comment]
Works Perfect!

This issue can be closed.
