### ISSUE TITLE
Не запускаются некоторые игры после обновления системы до Linux Mint 22 

### ISSUE THREAD

**Issue by mihail2245** [Kron4ek/Wine-Builds#141]
Здравствуйте.Возникла проблема с запуском некоторых игр через Wine на Linux Mint 22.Идет якобы запуск,делает вид,что хочет запуститься,но потом аварийно закрывается.До обновления дистрибутива ОС этого не было,а после началось.Не знаю, что делать.Проверены следующие игры Stalker Тень Чернобыля, Counter-Strike 1.6, Half-Life 1 и Need for Speed World Offline,эти игры не хотят запускаться нормально.Проверял другую,пока одну,The Sims 4,полет нормальный.Проблему сам не решил, надеюсь на вашу помощь

**Comment by Kron4ek** [comment]
32-битные библиотеки установлены в системе? Желательно 32-битный Wine установить, он подтянет большинство нужных библиотек:
```
$ sudo apt install wine32 wine64
```

**Comment by mihail2245** [comment]
> 32-битные библиотеки установлены в системе? Желательно 32-битный Wine установить, он подтянет большинство нужных библиотек:
> 
> ```
> $ sudo apt install wine32 wine64
> ```

Стоят,но не все библиотеки, использую бильды, которые беру отсюда из репозитория

**Comment by Kron4ek** [comment]
Установи `wine32`, если не установлен.

**Comment by mihail2245** [comment]
> Установи `wine32`, если не установлен.

Блин,у меня ж две версии для 32 и 64,а я конфиг не поставил

**Comment by mihail2245** [comment]
Нет,не хочет работать, некоторые игры всё ещё не работают,установил всё либы и пробовал 2 конфигурации wine,ничего,работают только некоторые игры

**Comment by Kron4ek** [comment]
Надо смотреть какие ошибки Wine пишет в терминале.

**Comment by Kron4ek** [comment]
Можно еще попробовать через [Conty](https://github.com/Kron4ek/Conty/releases) запустить, там внутри точно есть все нужные библиотеки.

**Comment by mihail2245** [comment]
> Можно еще попробовать через [Conty](https://github.com/Kron4ek/Conty/releases) запустить, там внутри точно есть все нужные библиотеки.

Сталкер удалось запустить,там увы пришлось скачать для Тень Чернобыля и Зов Припяти уже давно выпущен новый двиг, поставил, работает,под Half-Life и CS 1.6 wine не требуется,под Source тоже,я ранее скачивал эти игры,они уже переведены на Linux,мне хватает,ботов прикрутил,и нормально, буду продолжать проверку,какие игры будут работать,такие и буду через Wine использовать,а нет ,не странно,есть под Linux порты,запущу без проблем

**Comment by mihail2245** [comment]
Всё ясно.Я разобрался в проблеме.Причина проста,тут Wine не виноват,проблема в некоторых Windows играх,после обновления Linux Mint до версии 22,часть игр может не работать,это их проблема.Либы у меня все на месте.Буду дальше копаться в проблеме с играми,Wine не виноват

**Comment by mihail2245** [comment]
Проблема решена,причина найдена
