### ISSUE TITLE
Builds with wine-wayland support

### ISSUE THREAD

**Issue by porschemad911** [Kron4ek/Wine-Builds#144]
Thank you so much for providing wine binaries. We use the x86 binaries successfully in the ROCKNIX project in conjunction with box86 / box64 on ARM handhelds.

With the move to the sway compositor, I have been attempting to use the wayland driver in some game testing (via the method here: https://wiki.archlinux.org/title/Wine#Wayland but it seems to always be looking for an X display.

I'm not sure the `--with-wayland` build option is required, or if additional dependencies as described here are sufficient: https://gitlab.archlinux.org/archlinux/packaging/packages/wine/-/issues/11#note_157750

**Comment by Kron4ek** [comment]
My builds are already compiled with winewayland driver. I tried it on Sway, it works fine for me.

**Comment by porschemad911** [comment]
Thank you, must be something on our end, I'll do some more investigating. I'm getting:
```
0144:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0144:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
```

**Comment by porschemad911** [comment]
Builds already compiled with wine-wayland.
