### ISSUE TITLE
Battle.net crashing

### ISSUE THREAD

**Issue by mksaleem** [Kron4ek/Wine-Builds#145]
Thanks for the 9.17 Update. I'm just reporting an issue that started with the update 9.16 where battle.net refuses to launch completely and keeps crashing. it's been working fine till 9.15.
Can you please look into it
Thanks

**Comment by Kron4ek** [comment]
This is an upsteam bug.

https://bugs.winehq.org/show_bug.cgi?id=57098

**Comment by Kron4ek** [comment]
According to the bugreport, the issue should be fixed in Wine-Staging 9.18.
