### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by lucasmz1** [Kron4ek/Wine-Builds#147]
Can I use your wine to build my wine appimage, I have copied your repo but I'm a newbie here and I'm not getting how you build both wine and wine64 binaries!
your builds are better than the self wine deb files and even better than the one I make.
Hope you never give up from this project!

**Comment by Kron4ek** [comment]
Hello,

`create_ubuntu_bootstraps.sh` creates a build environment with all the needed build dependencies, `build_wine.sh` compiles Wine in this build environment.

**Comment by lucasmz1** [comment]
first, Thank you!
I've done this but I am not getting how to make this build over here: https://github.com/Kron4ek/Wine-Builds/releases/download/9.18/wine-9.18-amd64.tar.xz

I've made two local wine appimage build using this package and seems fine to me this build.

**Comment by lucasmz1** [comment]
which argument should I give to WINE_BRANCH= env var to build this version ?

**Comment by Kron4ek** [comment]
`vanilla`

**Comment by lucasmz1** [comment]
I tried that too. didn't work. thank you by the way.
closing this issue.
