### ISSUE TITLE
wine client error:77

### ISSUE THREAD

**Issue by Ahmed-E-86** [Kron4ek/Wine-Builds#15]
I get this error when I use the latest improved wine-staging build (5.6) when running Moon Of Madness:
`wine client error:77: read: Bad file descriptor`

- I don't encounter this issue when using wine-staging installed on my machine.
- I don't get this error when running other games using improved wine-staging build, only with this game.

**Comment by Kron4ek** [comment]
Does this errors happens with Improved 5.4 and 5.5 builds?

**Comment by Ahmed-E-86** [comment]
I tried using improved-wine on a different WINEPREFIX, it doesn't give me this error message, but it loads forever.

I think that this game require MF to load, and normal wine-staging skips that, and that is why it load successfully using normal wine-staging. I am not sure about that, but I found these messages when using normal wine-staging:
```
002f:fixme:mfplat:mfsource_CreatePresentationDescriptor (0000000001011E10)->(00000000005FDF60): stub
002f:fixme:mfplat:mfsource_Shutdown (0000000001011E10): stub
002f:fixme:mfplat:mfsession_Shutdown 0000000001009820.
002f:fixme:mfplat:standard_quality_manager_Shutdown 000000000100D6A0 stub.
```

**Comment by Kron4ek** [comment]
So the game works with your system Wine-Staging, could you please also try my Staging 5.6 build? Just to be sure that the problem is related to some patch(es) included in the Improved builds and not to my build environment.

**Comment by Ahmed-E-86** [comment]
> So the game works fine with Wine-Staging installed on your system (which is not my build?), could you please also try my Staging 5.6 build? Just to be sure that the problem is related to some patch(es) included in the Improved builds and not to my build environment.

Yeah, I want to try your normal wine-staging build, and previous improved wine-staging builds, but download speed is so limited at this time in my country, it will go back to normal in the morning.

**Comment by Ahmed-E-86** [comment]
Can you give me a link from Google Drive? The download speed from Github is so slow.

**Comment by Kron4ek** [comment]
Sure, [Staging 5.6 Google Drive](https://drive.google.com/open?id=1K18Ztd2rKuUrWlzsAEnQtrFdKkM7bCVT).

**Comment by Ahmed-E-86** [comment]
> Sure, [Staging 5.6 Google Drive](https://drive.google.com/open?id=1K18Ztd2rKuUrWlzsAEnQtrFdKkM7bCVT).

It works fine with your latest normal wine-staging build.

**Comment by Kron4ek** [comment]
Ok, so at least now we know that the issue is caused by some of the patch(es) from the Improved build.

I [compiled](https://drive.google.com/open?id=13-yXsSuaEJPzo88UYBL4zrEZsMs6nkmR) the build without the proton-winevulkan patch. This patch doesn't affect MF, but i think it may be related to your issue nonetheless.

**Comment by Kron4ek** [comment]
I downloaded the game and it hangs for me too with the Improved build. Disabling mfplat in winecfg allows the game to work.

Seems like the reason is the proton_mf_hacks patch, i will compile the build without it later to check this.

**Comment by Ahmed-E-86** [comment]
Great! Thanks.
