### ISSUE TITLE
[New patch request] HDR support patch for Remedy games: Alan Wake 2 at least.. (Control HDR mod also?)

### ISSUE THREAD

**Issue by oscarbg** [Kron4ek/Wine-Builds#150]
Hi,
If not late for next release can consider adding:

https://github.com/ValveSoftware/wine/commit/1182ef740346c62b76992f425593fa72e23203a7.diff

It’s a small patch.. applies cleanly..

In short allows Alan Wake 2 detecting HDR display (requires Gnome/KDE Wayland with HDR enabled and VK_hdr_layer + DXVK_HDR=1)
tested working..

For little more info see of when HDR was added in proton:
https://github.com/HansKristian-Work/vkd3d-proton/issues/1755

**Comment by Kron4ek** [comment]
Hi, yes, if it does not break anything i see no problems adding it.

**Comment by Kron4ek** [comment]
Added.
