### ISSUE TITLE
wine-9.19: Add  Install FFmpeg development libraries

### ISSUE THREAD

**Issue by zmtong1988** [Kron4ek/Wine-Builds#151]
Subsystem construction script(create_ubuntu_bootstraps.sh) add to:
  apt-get -y install libavutil libavformat libavcodec libswresample libswscale

**Comment by Kron4ek** [comment]
Why is this needed?

**Comment by zmtong1988** [comment]
> Why is this needed? According to the output of configure, these development files are already installed.
> 
> ```
> checking for libavutil/avutil.h... yes
> checking for libavformat/avformat.h... yes
> checking for libavcodec/avcodec.h... yes
> ```

https://gitlab.winehq.org/wine/wine/-/commit/6a9396549e946cdd924cb1211ccb3d8330267c7e

wine-9.19 run configure. The prompt subsystem is missing the FFmpeg library. Just install these libraries.

**Comment by Kron4ek** [comment]
I don't see such error in the output of configure.

**Comment by zmtong1988** [comment]
yes

**Comment by Kron4ek** [comment]
Thanks for the info anyway, didn't know Wine uses them now.
