### ISSUE TITLE
[New patch request] Bypass compositor in fullscreen modes from Proton

### ISSUE THREAD

**Issue by ndiruhniu** [Kron4ek/Wine-Builds#153]
Hi, Can I ask you to add [this](https://github.com/ValveSoftware/wine/commit/141ba5cf73029029a5a0bd2cdcfd5f9f9ab7ee7b) patch to tkg build? As I understand it, it can be included in [customization.cfg](https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/customization.cfg) on about line 146. This patch fixes alt+tab window switching in opengl games.

**Comment by ndiruhniu** [comment]
But it can be included in tkg build system and does not break anything.

**Comment by Kron4ek** [comment]
It can not, the tkg build system skips it for new Wine versions, even if you set the appropriate option to true in `customization.cfg`.

**Comment by ndiruhniu** [comment]
I didn't know, I'm sorry.

**Comment by Kron4ek** [comment]
No problem :)
