### ISSUE TITLE
"Bottle" is not created.

### ISSUE THREAD

**Issue by ndiruhniu** [Kron4ek/Wine-Builds#156]
"Bottle" is not created in Bottles with wine 9.22 stagin tkg amd64. Just endless creation of "Bottle".

**Comment by Kron4ek** [comment]
The build itself works fine on my system, i don't know why you have the issue with it in Bottles.

**Comment by ndiruhniu** [comment]
I don't understand why this happens. Wine 9.21 staging tkg amd64 is created in Bottles. Have you checked it there?
In the log everything stops at this:
```
Using Wine Runtime tool -- send_status(-i)
wineserver: using server-side synchronization.
```

**Comment by Kron4ek** [comment]
You can try to run it without Bottles and see if it works for you.

**Comment by ndiruhniu** [comment]
Yes, that's how it works, but I need to get it to work in Bottles. It's weird that this particular version doesn't work with it.

**Comment by ndiruhniu** [comment]
Возможно в этом проблема:
`/home/runner/build_wine/wine/dlls/win32u/sysparams.c:315: user_check_not_lock: Проверочное утверждение «0» не выполнено.`

**Comment by Kron4ek** [comment]
Does this issue occur on other 9.22 amd64 builds?

**Comment by ndiruhniu** [comment]
None of them work.

**Comment by Kron4ek** [comment]
And 9.21 worked fine, right? Seems like a regression in upstream Wine then.

**Comment by ndiruhniu** [comment]
Yes, wine 9.21 works fine.

**Comment by ndiruhniu** [comment]
Works with wine 10.0rc2 from Actions.
