### ISSUE TITLE
Suggetion add a wine build that uses https://gitlab.winehq.org/ElementalWarrior/wine/ (patches for affinity photo)

### ISSUE THREAD

**Issue by Totallynotmwa** [Kron4ek/Wine-Builds#158]
why i am requesting this???? 
Because this is a build that adds dxcore and fixes affinity on wine and the only way to use this is compiling it
reference:
https://forum.affinity.serif.com/index.php?/topic/182758-affinity-suite-v2-on-linux-wine/&/topic/182758-affinity-suite-v204-on-linux-wine/=

**Comment by Twig6943** [comment]
@Totallynotmwa https://github.com/Twig6943/ElementalWarrior-Wine-binaries

**Comment by Twig6943** [comment]
For more info https://github.com/Twig6943/affinityonlinux
