### ISSUE TITLE
Heroes of storm does not open with wine version, but it does with proton versions

### ISSUE THREAD

**Issue by aleex5** [Kron4ek/Wine-Builds#159]
In the wine versions it gives the error "Core: access permission", but in the proton versions it opens normally.

**Comment by Kron4ek** [comment]
If this issues affects not only my Wine builds, but Wine in general, then this is not the right place to report this bug.

**Comment by aleex5** [comment]
I don't really know if it's a specific wine error. I see old posts and the game worked with wine. I don't know if it's a missing dependency. The only thing I know is that compilations based on Valve's wine work fine. The other thing is that if I check the wine appdb, there are reports that it works. In fact, there's one from a not-so-old version, which is version 9.9, but I have no idea what causes this error.

[https://appdb.winehq.org/objectManager.php?sClass=version&iId=32232&iTestingId=115022](url)

In the wine tkg reports there are also reports that the game worked, I reported the error here because as these compilations include many patches, I thought that maybe there would be some proton patch that would fix this error.

[https://github.com/Frogging-Family/wine-tkg-git/issues/358#issuecomment-891827345](url)
