### ISSUE TITLE
Winetricks doesn't work with wine-staging-improved

### ISSUE THREAD

**Issue by Ahmed-E-86** [Kron4ek/Wine-Builds#16]
I can't use `winetricks` with the latest `wine-staging-improved` build (wine-staging 5.8)

It gives me this error message:

`wine cmd.exe /c echo '%AppData%' returned empty string, error message "" `

I tried to remove WINEPREFIX that I use with wine-staging-improved, and create a new one, but still gets the same error message.

**Comment by Ahmed-E-86** [comment]
The same happens with normal `wine-staging` installed on my system, and now I can't create any new wine prefix.

**Comment by Ahmed-E-86** [comment]
It is an issue with winetricks, and someone already reported it.

**Comment by Kron4ek** [comment]
Hmm, strange. The latest winetricks git version works fine for me with Wine-Staging 5.8.
