### ISSUE TITLE
New MinGW-w64 build 

### ISSUE THREAD

**Issue by rboxeur** [Kron4ek/Wine-Builds#160]
Hi Kron4ek,

I've just built a new MinGW-w64 build available here if you are interested based on latest MinGW-w64 git from today and Gcc-11.5.0 available at

http://techer.pascal.free.fr/Red-Rose_MinGW-w64-Toolchain/Red-Rose-MinGW-w64-Posix-Urct-v12.0.0.r458.g03d8a40f5-Gcc-11.5.0.tar.xz

Regards,

**Comment by Kron4ek** [comment]
Hi. Thank you, i will use it.
