### ISSUE TITLE
Wine-staging 5.13?

### ISSUE THREAD

**Issue by Ahmed-E-86** [Kron4ek/Wine-Builds#17]
There is something weird about wine-staging 5.13. This version didn't reach Ubuntu at all, the latest version is wine-staging 5.12, and that didn't happen before, and I can build wine 5.13 successfully, but `patchinstall.sh` always fails to add staging patches.

Also, you didn't add a new release for wine-staging as you always do. What is wrong with wine-staging 5.13?!

**Comment by Ahmed-E-86** [comment]
Wine-staging 5.13 is finally released for Ubuntu. Anyway, I don't care about a new release. I want to make sure that you are ok.

**Comment by Kron4ek** [comment]
Well, i don't know if there is anything wrong with Staging-5.13, i didn't add it because i didn't have access to my computer for a while. I will upload new releases soon.

**Comment by Ahmed-E-86** [comment]
Welcome back! I was worried something wrong might happen to you, you have been offline for quite sometime.
