### ISSUE TITLE
Wine-Tkg-Staging 5.15 = Broken (64 Bits)...winecfg returned two errors while initiating an empty WINEPREFIX

### ISSUE THREAD

**Issue by rboxeur** [Kron4ek/Wine-Builds#19]
I am on Xubuntu 20.04
I am using your builds for the 2 past years.
This is the first time when I ran winecfg that I met  wine errors.
I did it to initiate an empty WINEPREFIX
My Xubuntu is almost up-to-date
I did the same test with the build from Wine-Tkg from https://github.com/Frogging-Family/wine-tkg-git/releases
Got the same errors while running to winecfg
Downgraded to your build to wine-tkg-staging 5.14...winecfg ran successfully while initating an empty WINEPREFIX
From my perspective, either there is something wrong with my OS or there is a real error with 5.15.
Regards

**Comment by Kron4ek** [comment]
I get error during 64-bit prefix creation/updating too on Arch Linux (with both the official TkG build and with my build). Vanilla and Staging builds works fine, it's some of the patches in TkG build that cause the error. It seems that it's not a critical error though, 64-bit applications works fine. I will report to the TkG's issues tracker.

**Comment by rboxeur** [comment]
Hi Kron4ek,
Thanks for 

- replying so quickly 
- sharing these details. 
- filling a ticket 

I really appreciate it. Let's hope it can be fixed so we can close ticket here.
Regards,

**Comment by Kron4ek** [comment]
The issue has been fixed, i reuploaded 5.15-tkg builds.
