### ISSUE TITLE
Wine-Wayland Patches

### ISSUE THREAD

**Issue by nesper8** [Kron4ek/Wine-Builds#21]
Do you think you would be able to upstream patches from https://github.com/varmd/wine-wayland for wayland support?

**Comment by Kron4ek** [comment]
You mean add ability to compile wine-wayland builds to my build script? If yes, then the answer is yes, i think this is doable.

**Comment by nesper8** [comment]
yeah to add wine-wayland to your build scripts

**Comment by Kron4ek** [comment]
Ok, i [did](https://github.com/Kron4ek/Wine-Builds/commit/6d3236bdcb561286d21f2e7146c36b16bf679e8b) this. Also uploaded a test Wine-Wayland build, you can find it on the [releases](https://github.com/Kron4ek/Wine-Builds/releases) page.
