### ISSUE TITLE
Wine-wayland test build

### ISSUE THREAD

**Issue by Ahmed-E-86** [Kron4ek/Wine-Builds#22]
I tested your wine-wayland test build on KDE neon User Edition 5.20.2, and it opens two black windows during wine-boot, and nothing happens for quite some time, and I have to kill them both which ruins the whole wine-boot process.

KDE neon = Ubuntu LTS + the latest KDE Plasma

**Comment by Kron4ek** [comment]
Maybe these two windows are about "Mono" and "Gecko" installation.

What if you try to create a prefix with mshtml and mscoree disabled? Like this:

    export WINEDLLOVERRIDES="mshtml,mscoree="
    winecfg

**Comment by Kron4ek** [comment]
I just tested the latest build from the Wine-Wayland releases page, it has this issue too.

**Comment by nesper8** [comment]
Tested Dead Space 2 with wayland version
launches with black screen
![Grimshot 2020-10-30 17-56-21](https://user-images.githubusercontent.com/57890520/97705032-66cf0200-1ad9-11eb-99df-19fcc286599b.png)

**Comment by Kron4ek** [comment]
@nesper8 
I was able to run the game, there are again two windows, one of them is black, another is the game itself. However, mouse cursor in this game doesn't move, so i wasn't even able to skip the EA account creation window.

The full launch process in my case:

    export WINEPREFIX="${HOME}"/testprefix
    export WINEDLLOVERRIDES="mscoree,mshtml="
    export WINEARCH=win32
    export WINE="${HOME}"/wine-5.20-wayland-amd64/bin/wine
    export WINESERVER="${HOME}"/wine-5.20-wayland-amd64/bin/wineserver
    winetricks dxvk
    cd "${HOME}"/Games/"Dead Space 2"
    "${WINE}" deadspace2.exe

![ds2](https://user-images.githubusercontent.com/13851877/97711418-ea3f2200-1ade-11eb-829e-95ab6f5b061f.jpg)

**Comment by nesper8** [comment]
> there are again two windows, one of them is black, another is the game itself. However, mouse cursor in this game doesn't move, so i wasn't even able to skip the EA account login window.

can you try to focus the window in which the game is being shown and try pressing ModKey+F to make the focused window fullscreen or send unwanted windows to a different workspace with ModKey+LShift+{WorkspaceNumber} (ModKey+{WorkspaceNumber} to go to that workspace and you can also install grimshot from aur and add this to your sway config file to bind PrintScrn to take screenshots without needing to open a separate terminal window
`bindsym Print exec grimshot save screen`

**Comment by Kron4ek** [comment]
> can you try to focus the window in which the game is being shown and try pressing ModKey+F to make the focused window fullscreen or send unwanted windows to a different workspace with ModKey+LShift+{WorkspaceNumber} (ModKey+{WorkspaceNumber}

Tried both ways, unfortunately neither of these help with mouse. Also tried some Wine-Wayland specific variables, but they don't help with this either.
