### ISSUE TITLE
Wrong username in proton build

### ISSUE THREAD

**Issue by majorandras74** [Kron4ek/Wine-Builds#24]
Hi!

I see, the proton build uses the name "steamuser" as the username, while the other builds usually use the name of the user logged in to the system ($USER). For compatibility reasons, would it be possible for the proton build to use $USER as well?

Thanx

**Comment by Kron4ek** [comment]
Hello.

This is intended behavior, [it is](https://github.com/ValveSoftware/wine/commit/2e2a874cb3a44b2856561c0630037ea587177350) in the Proton sources.

> For compatibility reasons, would it be possible for the proton build to use $USER as well?

It is possible by reverting the appropriate commit, but i don't plan to do any modifications to Proton builds.
