### ISSUE TITLE
wine-6.0-rc3-staging-tkg-amd64.tar.xz seems a step back

### ISSUE THREAD

**Issue by shag00** [Kron4ek/Wine-Builds#26]
wine-6.0-rc2-staging-tkg-amd64.tar.xz could launch the game but frequent freezing this newer version (rc3) has no picture so cannot launch.

**Comment by Kron4ek** [comment]
Could you try to run your game with Staging (not tkg) 6.0-rc2 and 6.0-rc3 build, this will confirm if the issue is specific to tkg builds or not (of course, if the game can run on regular Staging builds at all).

Also, what game do you mean exactly?

**Comment by shag00** [comment]
Sorry, the game is Cyberpunk.  On non tkg rc2 game freezes on first startup screen, "Project CD Red" (in red font) while non tkg rc3 progresses a couple of screens further but still the red font intro screens.

**Comment by Kron4ek** [comment]
Hmm, i can't say what's the problem here, the game (version 1.05) works fine for me with both tkg-6.0-rc2 and tkg-6.0-rc3 (except some audio is missing in tkg-6.0-rc2 due to lack of SpatialAudio support).

Check [this](https://gitlab.freedesktop.org/mesa/mesa/-/issues/3960#note_735917) comment, maybe this will help.

**Comment by shag00** [comment]
Your link seems to be for AMD CPUs with AMD graphics. Red and AMD, with the 1.05 patch, have announced that the AMD throttle only affected 4 and 6 core processors so I am not affected and I also run a Nvidia 1080. I hope someone else has this problem and is able to provide the information you need to identify the issue. I have 2 PCs with exactly the same problem so I am sure it must be affecting others.

________________________________

**Comment by Kron4ek** [comment]
What about staging-tkg-6.0-rc4, does the game work for you with it?

**Comment by shag00** [comment]
Together with patch 1.06 it is a slight improvement, I probably get 10 minutes of game play before a freeze. It appears as if the game exe is still running but the graphics card gets turned off.

**Comment by shag00** [comment]
Tried basic 6.0-rc4 and tkg-6.0-rc4 with patch 1.06 with similar results. The game exe is running but the graphics card seems to just stop.

**Comment by shag00** [comment]
The release of the Linux Nvidia 460 driver seems to have fixed the issue.
