### ISSUE TITLE
I will recommend to upgrade to gcc 9.3.0 and mingw 8.0.0 using backport

### ISSUE THREAD

**Issue by rboxeur** [Kron4ek/Wine-Builds#27]
Hello Kron4ek,
First of all thanks for your work.
Now I am building my own packages using your shell scripts.
There are available on my own website http://www.davidgis.fr/blog/index.php 
Recently I discovered this backport for gcc-9.3.0 and mingw64 8.0.0
https://launchpad.net/~cybermax-dexter/+archive/ubuntu/mingw-w64-backport.

I took decision to give it a try and it seems to be really interesting instead of using the old gcc 8.4.0. - mingw 7.0.0
I built my wine builds  on my own chroots + gcc 9.3.0 + mingw64 8.0.0. And it works like a charm on my two laptops based on Xubuntu 20.04

I am sharing my own notes just in case you are interested...

Inside chroots
Amd64
======
# To fix libgcc-s1 issue before installing MinW64
wget http://mirrors.xmission.com/ubuntu/pool/main/g/gcc-10/libgcc-s1_10-20200411-0ubuntu1_amd64.deb
wget http://mirrors.edge.kernel.org/ubuntu/pool/main/g/gcc-10/gcc-10-base_10-20200411-0ubuntu1_amd64.deb
dpkg -i gcc-10-base_10-20200411-0ubuntu1_amd64.deb 
dpkg -i libgcc-s1_10-20200411-0ubuntu1_amd64.deb 
# Then Install the PPA
apt-get install software-properties-common
add-apt-repository ppa:cybermax-dexter/mingw-w64-backport
apt-get update
# After this line I didn't really remember what I did but maybe something lije below
apt-get install g++-mingw-w64-i686 g++-mingw-w64-x86-64 gcc-mingw-w64-base gcc-mingw-w64-i686 gcc-mingw-w64-x86-64

i686
====
# To fix libgcc-s1 issue before installing MinW64
wget http://mirrors.xmission.com/ubuntu/pool/main/g/gcc-10/libgcc-s1_10-20200411-0ubuntu1_i386.deb 
wget http://mirrors.edge.kernel.org/ubuntu/pool/main/g/gcc-10/gcc-10-base_10-20200411-0ubuntu1_i386.deb
dpkg -i gcc-10-base_10-20200411-0ubuntu1_i386.deb 
dpkg -i libgcc-s1_10-20200411-0ubuntu1_i386.deb
# Then install this PPA
apt-get install software-properties-common
add-apt-repository ppa:cybermax-dexter/mingw-w64-backport
# I didn't remember what I did...maybe a 'apt-get update + apt-get upgrade'

To Install GCC-9.3.0
=================
You can refer to this link 
https://www.ultralinux.org/post/how-to-install-gcc-compiler-on-ubuntu-18-04/

**Comment by Kron4ek** [comment]
Thank you for the information, i will use gcc 9.3.0 and mingw (8.0.0 + 9.3.0) to compile my builds. And the create_ubuntu_chroots.sh script now automatically adds these PPAs and installs gcc-9 and new mingw.
