### ISSUE TITLE
Boost Wine Build: Install ccache

### ISSUE THREAD

**Issue by rboxeur** [Kron4ek/Wine-Builds#28]
Hi Kron4ek,

I've just tried it and ccache helps a lot for the 2nd build of wine in the 32-bit chroot. It speeds up build time a lot.

# inside both chroots
apt-get install ccache -y

# To update environment variables CC, CXX, CROSSCC, CROSSCXX
# Please update to your needs accordingly. Idea is to add ccache before calling gcc or mingw64
for i in 32 64
do

        case ${ARCH_TYPE} in 
        amd64)
                echo $i | grep -q 64 && { _cflags=" -march=x86-64 -msse3 -mfpmath=sse -O2 "; cross_cc="x86_64-w64-mingw32-gcc"; cross_cxx="x86_64-w64-mingw32-g++"; }
                echo $i | grep -q 32  && { _cflags=" -march=i686 -msse2 -mfpmath=sse -O2"; cross_cc="i686-w64-mingw32-gcc"; cross_cxx="i686-w64-mingw32-g++"; }
                ;;
        esac

export CC="ccache gcc-9"
export CXX="ccache g++-9"
export CROSSCC="ccache ${cross_cc}";
export CROSSCXX="ccache ${cross_cxx}";
export CFLAGS=" ${_cflags} -pipe -ftree-vectorize"
export CXXFLAGS="${CFLAGS}"
export LDFLAGS="-Wl,-O1,--sort-common,--as-needed"
export CROSSCFLAGS="${CFLAGS}"
export CROSSLDFLAGS="-Wl,-O1,--sort-common,--as-needed"

done

**Comment by Kron4ek** [comment]
Good idea, thanks. Implemented with [42f7138](https://github.com/Kron4ek/Wine-Builds/commit/42f71389888dc2edd58c7d4cfba6e3e3d99c3cb4).
