### ISSUE TITLE
Don work on  32bit wine on Ubuntu 20.04

### ISSUE THREAD

**Issue by anwarmax-cpu** [Kron4ek/Wine-Builds#29]
[log of the error.docx](https://github.com/Kron4ek/Wine-Builds/files/5866712/log.of.the.error.docx)
In wine64  side everything  works  except  graphic  problem  on some games  like rise of the Tomb rider  and  watch  dogs  1 I don't  know  if it is my gpu or  wine  but my main problem is on wine32 (./wine)  it opens winecfg,cmd,and regediter  but on others  it throws  use Truetype  font please install  a version of freetype  greater than or equal to 2.0.5.  
I have  installed  it but I don't  know  how  to  install   32bit  version 

My spec 
Intel  core i5 3340m 
Intel  hd 4000 
4gb  ram
10 gb swap  virtual  memory

**Comment by Kron4ek** [comment]
You can install 32-bit version of freetype with this command:

`sudo apt install libfreetype6:i386`

And i recommend to install wine32 package to get all required dependencies:

`sudo apt install wine32`

**Comment by anwarmax-cpu** [comment]
ok thanks  I will try

**Comment by anwarmax-cpu** [comment]
it actually  worked thanks   my issue  is resolved
