### ISSUE TITLE
wine-6.0-staging-tkg-amd64 video off and on when playing Cyperpunk 2077

### ISSUE THREAD

**Issue by shag00** [Kron4ek/Wine-Builds#30]
wine-6.0-rc4-staging-tkg-amd64 seems to have lost something in wine-6.0-staging-tkg-amd64. On the rc4 version things are pretty good on one PC (30 minutes play time without a problem) and frequent game freezes on another PC with different hardware (though same Nvidia GPU) and same software, Kubuntu 20.10.

Anyway, if I play cyberpunk with the 6.0 version (not rc4) the screen goes black for several seconds, then returns to normal for a few seconds and keeps repeating this behaviour. Game does not work at all on 5.13 experimental.

**Comment by Kron4ek** [comment]
This is strange. As far as i can tell, there were no major changes between 6.0-rc4 and 6.0, not even on TkG and Staging sides, mostly bugfixes. 

And unfortunately i removed Cyberpunk a few days ago as i needed more disk space, so at least for now i can't tell if i have the same issue or not.

**Comment by Kron4ek** [comment]
By the way, do you create a new prefix for each new Wine version or use a previously created prefix? If the latter, try to create a new clean prefix using the latest wine-staging-tkg, maybe this will help.

**Comment by shag00** [comment]
I use a common wine prefix for a few old programs I use, a couple of which do not have a GUI and work reliably with standard wine but for newer programs and all games it's always a separate prefix. After some more experience I also think this issue may be related to the release of the Nvidia 460 driver as they did not install cleanly.

**Comment by gabriele2000** [comment]
> By the way, do you create a new prefix for each new Wine version or use a previously created prefix? If the latter, try to create a new prefix using the latest wine-staging-tkg, maybe this will help.

By the way, I found a quick way to recreate the prefix without losing anything, except for the custom set dll.
You basically have to delete every file except the folder "drive_c", then navigate inside it and delete the "windows" folder.
Then type "winecfg" or "wineboot -u" and you're good to go.

You maybe want to mention this in the readme, it's useful as hell

**Comment by Kron4ek** [comment]
I downloaded Cyberpunk 2077 again for testing and it works fine for me on Staging and Staging-TkG 6.9.
