### ISSUE TITLE
Multiple issues with latest versions of Wine-TKG

### ISSUE THREAD

**Issue by Ahmed-E-86** [Kron4ek/Wine-Builds#31]
I encountered 2 issues with the latest Wine-tkg that do not exist with latest Wine-staging, or Wine-tkg 5.20.

1- I encountered an issue with Detroit Become Human, and Cloudpunk, these games do not see the save games, and want to start a new one (the save game exists inside the wineprefix).

2- I encountered another issue with many games, these games are run with WineD3D instead of DXVK (DXVK is installed inside the wineprefix).

**Comment by Kron4ek** [comment]
I downloaded Cloudpunk, and at least for me it works fine and sees its saves with the latest wine-tkg 6.1. I can't test Detroit Become Human though as i just don't have enough disk space at the moment.

Do you use already created prefix (i mean created with older Wine version)? And if so, could you try to create a new prefix using the latest wine-tkg?

**Comment by Ahmed-E-86** [comment]
I created a new prefix, and that fixed these issues, and another issue with the controller I had with a few games. Sorry to bother you, and thanks for your help.

**Comment by Kron4ek** [comment]
No problem. The wine's prefix auto-update feature usually works fine, but sometimes it causes some weird issues, i have ecountered some issues a few times because of it.

**Comment by Ahmed-E-86** [comment]
I still have an issue with the latest wine-tkg. When I use mangohud, some games do not launch, and stops without any erros. That does not happen with the latest wine-staging.

**Comment by Kron4ek** [comment]
I can't reproduce this in Yooka-Laylee and the Impossible Lair, tried multiple times. But since you say it happens randomly, my experience doesn't say much here. Does it happen often for you?

**Comment by Ahmed-E-86** [comment]
Yeah, it happens a lot especially with Detroit Become Human. I use this PPA for mangohud >> https://launchpad.net/~flexiondotorg/+archive/ubuntu/mangohud
I will just compile it from the source, and see if it makes any difference.

**Comment by Kron4ek** [comment]
You can also try the official MangoHud build from the [releases](https://github.com/flightlessmango/MangoHud/releases) page. 

Here is how you can use it:

1. Extract libMangoHud.so, libMangoHud_dlsym.so and MangoHud.json to any desired directory. 
2. Edit MangoHud.json, replace path in the library_path to the actual path to libMangoHud.so. For example:
`"library_path": "/home/username/MangoHud/libMangoHud.so"`
3. Now you can enable with this variables:

```
export VK_LAYER_PATH=/home/username/MangoHud
export VK_INSTANCE_LAYERS="VK_LAYER_MANGOHUD_overlay"

wine app.exe
```

Replace "/home/username/MangoHud" with the actual path where you extracted the MangoHud files.
