### ISSUE TITLE
"weird" issues with Wine-staging-tgk-amd64 6.5 and Wine-staging-tgk-amd64 6.6

### ISSUE THREAD

**Issue by gabriele2000** [Kron4ek/Wine-Builds#34]
First issue: Steam (windows version) won't create the shortcut as .desktop files like wine-staging used to do, so far this issue occur both on 6.5 and 6.6.
Second issue (the worst so far): when installed, steam (could be everything else) creates a shortcut on the application menu, the usual .desktop file. Basically I had to change a line from `wine start /Unix "/home/gabriele/.wine/drive_c/Program Files (x86)/Steam/steam.exe"` to `Exec=wine  "/home/gabriele/.wine/drive_c/Program Files (x86)/Steam/steam.exe"`.
The bad thing is that this issue led to a manual creation of a "/opt/wine-staging/bin/wine %U" argument so I could launch applications and games through double-click.
Could those problem be related to the fact that you simply have to copy the files instead of installing wine?

EDIT: Stupid brain, I just figured something out: "winemenu something" is disabled by your build config, so the first problem is that, while the second problem relies on a wine 6.5 bug, still not solved in wine 6.6, but I think that the change I had to make is related to the first problem

**Comment by Kron4ek** [comment]
Right, winemenubuilder is disabled in my builds, so .desktop files (including the ones required for launching by double-click) are not created or updated automatically. And you are right, "start /Unix" was broken in 6.5 release, but should be fixed in 6.6 (according to the changelog at least).

> The bad thing is that this issue led to a manual creation of a "/opt/wine-staging/bin/wine %U" argument so I could launch applications and games through double-click.

You can add a custom Wine build's bin directory to your PATH variable, in this case you can use just "wine" instead of specifying the full path like "/opt/wine-staging/bin/wine"

For example:
```
export PATH="/opt/wine-staigng/bin:${PATH}"
wine --version
```

**Comment by gabriele2000** [comment]
> Right, winemenubuilder is disabled in my builds, so .desktop files (including the ones required for launching by double-click) are not created or updated automatically. And you are right, `start /Unix` is broken in 6.5 release and is only partially fixed in 6.6. The next release should include a complete fix.
> 
> > The bad thing is that this issue led to a manual creation of a "/opt/wine-staging/bin/wine %U" argument so I could launch applications and games through double-click.
> 
> You can add a custom Wine build's bin directory to the beginning of your PATH variable, in this case you can use just "wine" instead of specifying the full path like "/opt/wine-staging/bin/wine".
> 
> For example:
> 
> ```
> export PATH="/opt/wine-staging/bin:${PATH}"
> wine --version
> ```
> 
> This will not help with `start /Unix` of course, but may be useful anyway.

All right, thanks for the explanation...
For winemenubuilder, could I enable it after wine installation or is there something else I can do to fix this?

**Comment by Kron4ek** [comment]
> For winemenubuilder, could I enable it after wine installation or is there something else I can do to fix this?

You can copy it from some other Wine build that includes it, this should work i guess. For instance, copy it from you system-wide Wine if it's installed:

```
cp /usr/lib/wine/fakedlls/winemenubuilder.exe wine-6.6-staging-tkg-amd64/lib64/wine/fakedlls
cp /usr/lib/wine/winemenubuilder.exe.so wine-6.6-staging-tkg-amd64/lib64/wine
cp /usr/lib32/wine/fakedlls/winemenubuilder.exe wine-6.6-staging-tkg-amd64/lib/wine/fakedlls
cp /usr/lib32/wine/winemenubuilder.exe.so wine-6.6-staging-tkg-amd64/lib/wine
```

And then update your prefix:
```
wine-6.6-staging-tkg-amd64/bin/wineboot -u
```

**Comment by gabriele2000** [comment]
> > For winemenubuilder, could I enable it after wine installation or is there something else I can do to fix this?
> 
> You can copy it from some other Wine build that includes it, this should work i guess. For instance, copy it from your system-wide Wine if it's installed:
> 
> ```
> cp /usr/lib/wine/fakedlls/winemenubuilder.exe wine-6.6-staging-tkg-amd64/lib64/wine/fakedlls
> cp /usr/lib/wine/winemenubuilder.exe.so wine-6.6-staging-tkg-amd64/lib64/wine
> cp /usr/lib32/wine/fakedlls/winemenubuilder.exe wine-6.6-staging-tkg-amd64/lib/wine/fakedlls
> cp /usr/lib32/wine/winemenubuilder.exe.so wine-6.6-staging-tkg-amd64/lib/wine
> ```
> 
> And then update your prefix:
> 
> ```
> wine-6.6-staging-tkg-amd64/bin/wineboot -u
> ```

Confirmed, it works!
Damn, thanks a lot, you're awesome
