### ISSUE TITLE
Warframe dx12 option missing with wine-staging 6.7 

### ISSUE THREAD

**Issue by jhu54** [Kron4ek/Wine-Builds#35]
Running Warframe through Lutris with a custom runner pointing to wine-6.6-staging-tkg-amd64/bin/wine64 and in the launcher options, dx12 experimental is available. Switch runner to wine-6.7-staging-tkg-amd64/bin/wine64 and the launcher no longer has a dx12 experimental option, just dx11. World of Warcraft through Lutris with the 6.7 runner works fine with dx12. I just checked using wine-6.7-staging/bin/wine64 and wine, and have the same issue. Any ideas on what I can try or is this an upstream issue introduced in the current build of wine?

**Comment by Kron4ek** [comment]
I can confirm that DX12 is missing from the Warframe launcher options with Wine 6.7 release (vanilla is affected too). This is an upstream issue so it's better to report this to [WineHQ](https://bugs.winehq.org/). I don't know how to work around this issue, so i suggest to use 6.6 for Warframe for now.

**Comment by jhu54** [comment]
Thx

**Comment by jhu54** [comment]
Funny after all their bitching that this wasn't a Wine bug, it was fixed with 6.8 vanilla... Still can't get it to work with their dxvk though I suspect it is because I am not really trying that hard :)
