### ISSUE TITLE
[Fixed] Your Proton 6.3-3 is broken, here is the fix

### ISSUE THREAD

**Issue by rboxeur** [Kron4ek/Wine-Builds#36]
Hi Kron4ek,

Your Proton 6.3-3 is broken and may not work for all games. You may got something like.
Killed Process

Culprit are the 3 latests commits in Wine from Proton.
You may have to reverse them

```
cd /opt/Sources/Proton-Experimental-6.3/wine/
git format-patch -r -n3 a80652ca4c8d69591e3242019e487502510323ea
patch -R -Np1 -i /opt/Sources/Proton-Experimental-6.3/wine/0001-server-Do-not-cancel-process-sigkill-in-kill_process.patch
patch -R -Np1 -i /opt/Sources/Proton-Experimental-6.3/wine/0002-server-Add-sigkill-timer-even-if-msg_fd-is-closed.patch
patch -R -Np1 -i /opt/Sources/Proton-Experimental-6.3/wine/0003-ntdll-Close-server-socket-before-calling-exit.patch

```

Hope it helps
Regards

**Comment by Kron4ek** [comment]
You are right, some games get instantly killed on launch (in my testing, at least Factory Town is affected), reverting these commits fixes the issue . Thank you.

I guess Valve will release 6.3-4 soon, since the official Proton build should also be affected.
