### ISSUE TITLE
Thank you! :)

### ISSUE THREAD

**Issue by frostworx** [Kron4ek/Wine-Builds#37]
Hey Kron4ek!
It has been [a while](https://github.com/Kron4ek/Conty/issues/1), I hope you're fine.
I just found your Wine-Builds project via [this imho very important fix](https://github.com/ValveSoftware/Proton/issues/4808#issuecomment-835416513) and would like to thank you for providing those packages - it is always good to have a choice :)
If you don't mind I'd like to also add support for both your wine and proton packages into my [steamtinkerlaunch](https://github.com/frostworx/steamtinkerlaunch).
Keep up your great work! :+1:

**Comment by Kron4ek** [comment]
Hi frostwork,

You are welcome! Having a choice is a good thing indeed :)

> If you don't mind I'd like to also add support for both your wine and proton packages into my steamtinkerlaunch.

Sure, i don't mind. 

Just for information, my Proton (and Wine too, of course) builds don't include built-in DXVK and vkd3d-proton, so to use these builds inside Steam (i haven't tested this use-case though), dxvk and vkd3d-proton need to be manually copied from the official Proton build, or downloaded directly from their github repos. I mean these directories:

```
~/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib(64)/wine/dxvk
~/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib(64)/wine/vkd3d-proton
```

**Comment by frostworx** [comment]
Hey @Kron4ek,
thanks for the quick reply! Looks like you already answered my [Feature Request](https://github.com/Kron4ek/Wine-Builds/issues/38) with it :) *(will close it after my reply here)*.
Thanks for the info. I'll add support for your wine packages in any case, and see what I can do to add an automated or gui-based merge for your proton packages and custom dxvk, vkd3d-proton and other proton files.
