### ISSUE TITLE
FSYNC strange issue: is wine /start garbage compared to wine "program.exe"?

### ISSUE THREAD

**Issue by gabriele2000** [Kron4ek/Wine-Builds#39]
So... I'm using your build since 2 months and only a few days ago I realized: fsync is not being used, I'm a fool.
I set the variable in .bashrc so everything uses it, no man's sky (pure vulkan game, no DXVK) is still slow as hell.
Then I realized something: if I run `wine NMS.exe` fsync will start, steam will start and the game will open, in the fastest way I could possibly imagine, before that first try it was slooooooowwwwwwww. Yes I own the game so steam is required.

BUT if I open steam, through the shortcut and then open the game inside steam, fsync will not start, that's because that shortcut has `wine /start /unix something path to "steam.exe"` and it breaks everything.
I connect every game to steam, so I can create a shortcut through it, so the icon will be present and my friends can see me online while playing and maybe join me.

How can I fix it?
Keep in mind that every shortcut is like this `env WINEPREFIX="/home/gabriele/.wine" /opt/wine-staging/bin/wine C:\\\\windows\\\\command\\\\start.exe steam://rungameid/15531102088879669248` basically that start.exe is stupidly broken in my honest opinion

**Comment by gabriele2000** [comment]
> > wine /start /unix something path to "steam.exe"
> 
> What if you try to run this exact command in terminal, do you see `fsync: up and running` there?

Both `env WINEPREFIX="/home/gabriele/.wine" /opt/wine-staging/bin/wine C:\\\\windows\\\\command\\\\start.exe steam://rungameid/275850` (no man's sky) and `env WINEPREFIX="/home/gabriele/.wine" /opt/wine-staging/bin/wine C:\\\\windows\\\\command\\\\start.exe /Unix /home/gabriele/.wine/dosdevices/c:/users/Public/Desktop/Steam.lnk` (steam) gives the good result: `fsync: up and running`

Now, double clicking the shortcut produces the incorrect result... why?
That doesn't make much sense

**Comment by Kron4ek** [comment]
So No Man's Sky runs with good performance if you run the above commands in terminal, and it runs slow if you run Steam and the game though the shortcuts (even though they contain the same commands), right?

**Comment by gabriele2000** [comment]
> So No Man's Sky runs with good performance if you run the above commands in terminal, and it runs slow if you run Steam and the game though the shortcuts (even though they contain the same commands), right?

Exactly

**Comment by gabriele2000** [comment]
> Does adding WINEFSYNC to the shortcuts help? Like:
> 
> ```
> env WINEFSYNC=1 WINEPREFIX="/home/gabriele/.wine" /opt/wine-staging/bin/wine C:\\\\windows\\\\command\\\\start.exe /Unix /home/gabriele/.wine/dosdevices/c:/users/Public/Desktop/Steam.lnk
> ```

It fixes the problem, still, I added `export WINEFSYNC=1` to .bashrc and it doesn't help at all...
Is there some kind of way to set this on by default even when double-clicking?

**Comment by Kron4ek** [comment]
Well, .bashrc only get executed by interactive bash instances. So if you want to set it globally, you can add it to /etc/enviroment, for example, or you can try to add it to ~/.profile, ~/.bash_profile or /etc/profile.

**Comment by gabriele2000** [comment]
> you can try to add it to ~/.profile

that fixed everything, thanks a lot
