### ISSUE TITLE
A few questions about Proton 4.11

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [Kron4ek/Wine-Builds#4]
I have a few questions in mind that I don't have an answer for

1- How can I use Fsync with your Proton build version 4.11?

2- Do I need to use your FAudio builds with it to be able to use FAudio? Or is it like normal Wine builds that use FAudio installed in my system?

I use KDE Neon (Ubutnu 18.04), and I use this external repository for FAudio
https://launchpad.net/~cybermax-dexter/+archive/ubuntu/sdl2-backport

**Comment by Kron4ek** [comment]
> How can I use Fsync with your Proton build version 4.11?

According to Proton's source code it can be enable using WINEFSYNC=1 env variable.

> Or is it like normal Wine builds that use FAudio installed in my system?

Yes, these Proton builds use FAudio installed in your system, just like normal Wine builds.

**Comment by ahmed-elsayed2017** [comment]
That is good news. Thanks.
