### ISSUE TITLE
Questions about AMD FSR

### ISSUE THREAD

**Issue by Ahmed-E-86** [Kron4ek/Wine-Builds#42]
First, thanks for including AMD FSR in your Wine builds.

I have 2 questions about AMD FSR if you do not mind:

1- You said in release note that is `WINE_FULLSCREEN_FSR_STRENGTH` controls sharpening, 0 is the maximum, and 5 is the minimum. Is it a typo, or is it right this way?

2- How can I control resolution?

**Comment by Kron4ek** [comment]
>  You said in release note that is WINE_FULLSCREEN_FSR_STRENGTH controls sharpening, 0 is the maximum, and 5 is the minimum. Is it a typo, or is it right this way?

Not a typo, lower numbers really mean more sharpening.

> How can I control resolution?

By changing in game resolution. Any lower than native resolution will be automatically upscaled to your native resolution. And it's important to enable fullscreen mode (not borderless window) in game settings.

For example, if your native display's resolution is 1920x1080 and you choose 1280x720 in game settings, the image will be upscaled from 1280x720 to 1920x1080.

**Comment by Ahmed-E-86** [comment]
Thanks for clearing that up.
