### ISSUE TITLE
VKD3D-Proton question

### ISSUE THREAD

**Issue by gabriele2000** [Kron4ek/Wine-Builds#43]
First of all: since wine-tgk is basically wine + proton + various hacks, is VKD3D present or I was wrong thinking that tgk is wine + proton?

Asking because `err:module:open_builtin_so_file failed to load .so lib "/usr/lib/wine/x86_64-unix/d3d12.dll.so"
`

**Comment by Kron4ek** [comment]
You are right, wine-tkg includes Proton patches (maybe not all, but many of them). However, vkd3d-proton is not included, you need to manually [install it](https://github.com/HansKristian-Work/vkd3d-proton/releases) into your Wine prefix, like you do with DXVK.

**Comment by gabriele2000** [comment]
> You are right, wine-tkg includes Proton patches (maybe not all, but many of them). However, vkd3d-proton is not included (since it's a separate submodule, not a patch), you need to manually [install it](https://github.com/HansKristian-Work/vkd3d-proton/releases) into your Wine prefix, like you do with DXVK.
> 
> The same with my Wine-Proton builds. Even though they include all of the Proton patches, separate submodules (like dxvk and vkd3d) are not included and need to be manually installed into a Wine prefix.

Oh, thanks a lot, now it works!
Another question: since WMV support is still missing or, at least, complete at 40% maybe, are the patches for that codec support available in wine-tgk?

**Comment by Kron4ek** [comment]
Afaik, no, wine-tkg has the same level of wmv support as the regular wine-staging.

**Comment by gabriele2000** [comment]
> Afaik, no, wine-tkg has the same level of wmv support as the regular wine-staging builds.

Who has the most recent changes? Proton or Wine? Because I know that Proton is making progress on the WMV support, still nothing from wine, as far as I know

**Comment by Kron4ek** [comment]
I don't know for sure, but i guess Proton Experimental has better support for WMV decoding.

**Comment by gabriele2000** [comment]
> I don't know for sure, but i guess Proton Experimental has better support for WMV decoding.
> 
> Make sure that you have gstreamer plugins (base, good, bad, ugly) installed, including their 32-bit versions for 32-bit games. Because both Proton and Wine-Staging rely on the gstreamer plugins for Media Fundation support.

all right, thanks a lot, for everything!
