### ISSUE TITLE
Building against libjpeg 6.2?

### ISSUE THREAD

**Issue by refi64** [Kron4ek/Wine-Builds#45]
Right now the compiled binaries require libjpeg8 in order to run, without that being installed you get messages like:

```
00fc:err:wincodecs:jpeg_decoder_create Failed reading JPEG because unable to find libjpeg.so.8
```

However, libjpeg8 isn't available any more on many distros (neither Fedora nor recent Debian versions have it). Would it be possible for the binaries to be built using libjpeg 6.2 instead? `libjpeg-turbo62` seems to have much wider availability...

**Comment by Kron4ek** [comment]
I think it's possible to build with libjpeg62 since Ubuntu 18.04 (which i use for compilation) has it in the repos, i will try to compile the next release with it. That will break TIFF support though, don't know if many Windows apps require it.

**Comment by Kron4ek** [comment]
I uploaded wine-proton 6.3-7, which i compiled against libjpeg62. And the next Wine release will be probably compiled using libjpeg62, unless new issues arise.

**Comment by Kron4ek** [comment]
New release is uploaded, compiled against libjpeg62.
