### ISSUE TITLE
Possible upstream wine bug?

### ISSUE THREAD

**Issue by frostworx** [Kron4ek/Wine-Builds#46]
Hi there,
this is not really your bug, but I thought it might be a good idea to mention it here, as you might be interested as well
and for sure would find the reason much faster than me. Sorry, if opening this issue is unappropriated!

I stumbled over a possible wine bug _(no idea if it is already known somewhere)_ where any wine version/variant
above `wine-6.17.$COMMITX` doesn't detect valid directories as directories _(at least in Vortex Mod Manager)_.
I tried to sum up the problem on my steamtinkerlaunch issue ticket [here](https://github.com/frostworx/steamtinkerlaunch/issues/312)

If interested, any help/pointer would be great. If there's anything I can do to help, please let me know!

~~Just added this:~~
~~**EDIT: Wait what!**~~

~~- `wine-6.17.r0.g5f19a815 ( TkG Staging Esync Fsync )`  from wine-6.17-staging-tkg-amd64  by @Kron4ek **works but the same version from proton above doesn't? Let me retest!**~~

Sorry for the noise...

**Comment by frostworx** [comment]
Hey, @Kron4ek!
Nice to meet you again :)
Thank you very much for your interest and your fast reaction!

I just tried to reproduce my last "finding" that it does not work with `proton_tkg_6.17.r0.g5f19a815.release/files/bin/wine`
but does with `wine/wine-6.17-staging-tkg-amd64/bin/wine` _(both `wine-6.17.r0.g5f19a815 ( TkG Staging Esync Fsync )`)_
but I could not reproduce this, so I might have tested wrong in between.

**Comment by Kron4ek** [comment]
> but I could not reproduce this, so I might have tested wrong in between.

Probably. I can't reproduce the issue with proton_tkg_6.17.

**Comment by frostworx** [comment]
> Probably. I can't reproduce the issue with proton_tkg_6.17.

I couldn't as well. Sorry for the misleading testresult.

**Comment by frostworx** [comment]
Very likely the upstream bug: https://bugs.winehq.org/show_bug.cgi?id=51816

**Comment by Kron4ek** [comment]
I found out that the first bad commit is https://github.com/wine-mirror/wine/commit/984f608c2885c80284ca8f35d6ad72d5193b3658. Most likely this is the only commit that causes the issue, but i can't say for sure since i can't revert it because of conflicts.

**Comment by frostworx** [comment]
Wow, thank you very much for your excellent work, @Kron4ek :)

**Comment by frostworx** [comment]
*closing here* thanks again!

**Comment by frostworx** [comment]
Sorry for the late reply! I've seen that the bug was closed/fixed recently. Thanks again for reporting it!
Happy holidays,a happy new year and stay save!

**Comment by Kron4ek** [comment]
Happy holidays to you too, @frostworx.
