### ISSUE TITLE
Proton builds ignore WINEPREFIX

### ISSUE THREAD

**Issue by Simon-L** [Kron4ek/Wine-Builds#5]
It seems the Proton builds ignore the prefix environment variable. No matter what I set and however I set it, Proton always uses the default `~/.wine` prefix.
`WINEPREFIX=/path/to/custom/prefix /opt/wine-4.11-3-proton-amd64/bin/winecfg`
shows as if launched as:
`WINEPREFIX=~/.wine /opt/wine-4.11-3-proton-amd64/bin/winecfg`
Tested with your builds of Proton 4.2-8 and 4.11-3, behaviour is as expect with standard wine using your build of 4.15.

Is this issue related to https://github.com/ValveSoftware/Proton/wiki/Proton-FAQ#how-does-proton-manage-wine-prefixes ?

**Comment by Simon-L** [comment]
Just noticed the new builds from today, will try.

**Comment by Kron4ek** [comment]
That's weird, i can't reproduce this issue. I just tried different Proron builds (3.16-8, 4.2-8 and 4.11-4) and they are all properly handle WINEPREFIX env variable. For example, i get this output with Proton 4.11-4 with specified WINEPREFIX:

    $ WINEPREFIX=/home/user/testprefix wine-4.11-4-proton-amd64/bin/winecfg
    wine: created the configuration directory '/home/user/testprefix'
    wineserver: using server-side synchronization.
    wine: configuration in '/home/user/testprefix' has been updated.

Are you sure that nothing else overrides your WINEPREFIX variable?

**Comment by Kron4ek** [comment]
Closing due to lack of feedback.
