### ISSUE TITLE
New futex usage

### ISSUE THREAD

**Issue by gabriele2000** [Kron4ek/Wine-Builds#50]
Basically I'd like to know how to use the new implementation of Futex present on xanmod-kernel (5.16 kernel future patch)

**Comment by Kron4ek** [comment]
Currently only Proton 6.3 Experimental builds support the FUTEX2 (futex_waitv) impelentation. As usual, you need to enable `WINEFSYNC` and futex_waitv will be used by default (and can not be disabled) if your kernel supports it.

**Comment by Kron4ek** [comment]
Currently only recent Proton 6.3 Experimental builds support the new futex_waitv implementation. As usual, you need to enable the `WINEFSYNC` env variable and futex_waitv will be used if your kernel supports it.

What's also important is that the old futex_wait_multiple and FUTEX2 implementations have been removed from Proton Experimental, and now it's only possible to use FSYNC if the kernel supports futex_waitv. So if you see:

```
fsync: up and running.
```
Then the new implementation is being used.

You can try [my Proton Experimental build](https://github.com/Kron4ek/Wine-Builds/releases/tag/6.3-proton-exp) and see if fsync works for you.

**Comment by gabriele2000** [comment]
> What's also important is that the old futex_wait_multiple and FUTEX2 implementations have been removed from Proton Experimental, and now it's only possible to use FSYNC if the kernel supports futex_waitv.

What about WINE? Will it be supported, for example, in the next release?

**Comment by Kron4ek** [comment]
You mean in upstream Wine? I don't know for sure, but i think it will be added to Wine-Staging at some point.

There is a already [a patch](https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-patches/proton/fsync_futex_waitv.patch) for futex_waitv support in the wine-tkg repo, so it is possible to compile a custom Wine build with it.

**Comment by gabriele2000** [comment]
> You mean in upstream Wine? I don't know for sure, but i think it will be added to Wine-Staging at some point.
> 
> By the way, there is already [a patch](https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-patches/proton/fsync_futex_waitv.patch) for futex_waitv support in the wine-tkg repo, so it is possible to compile custom Wine builds with it. Maybe i will add it to my staging-tkg build in the next release.

Yes please, the disappearance of futex2 support causes a lot of issues ("old" fsync thank you) that the new fsync implementation will again remove, such as the famous keyboard delay with high CPU-intensive tasks

**Comment by Kron4ek** [comment]
Uploaded a new release, futex_wativ is now included in staging-tkg.

**Comment by rauldipeas** [comment]
> Currently only recent Proton 6.3 Experimental builds support the new futex_waitv implementation. As usual, you need to enable the `WINEFSYNC` env variable and futex_waitv will be used if your kernel supports it.
> 
> What's also important is that the old futex_wait_multiple and FUTEX2 implementations have been removed from Proton Experimental, and now it's only possible to use FSYNC if the kernel supports futex_waitv. So if you see:
> 
> ```
> fsync: up and running.
> ```
> 
> Then the new implementation is being used.
> 
> You can try [my Proton Experimental build](https://github.com/Kron4ek/Wine-Builds/releases/tag/6.3-proton-exp) and see if fsync works for you.

I'm getting this message with 7.0-rc1 TkG Staging and XanMod LTS.
```
wineserver: using server-side synchronization.
```

Nothing related to `fsync` it's showed on shell log.

**Comment by Kron4ek** [comment]
@rauldipeas Xanmod 5.10 LTS does not support futex_waitv.

**Comment by rauldipeas** [comment]
> @rauldipeas Xanmod 5.10 LTS does not support futex_waitv. You need xanmod 5.15 for fsync to work.

Audio stuff that I use to work become unstable on 5.15, there's any workaround?

**Comment by Kron4ek** [comment]
> Audio stuff that I use to work become unstable on 5.15, there's any workaround?

Sorry, don't know if there are any workarounds for your issue. 

And regarding Wine and Fsync, you can use older staging-tkg versions (6.22 and older), they support old futex_wait_multiple interface, so Fsync will work even on xanmod 5.10. That is if you would like to avoid using 5.15 but still want to use fsync.

**Comment by rauldipeas** [comment]
Solved.
![image](https://user-images.githubusercontent.com/12108031/146649597-9eee7235-40e2-44cb-ba0f-6b76ff85bd5c.png)
