### ISSUE TITLE
How would I compile without the fshack patch?

### ISSUE THREAD

**Issue by windowsrefund** [Kron4ek/Wine-Builds#51]
Hello,
Thanks for providing the build_wine.sh script. I'd like compile staging-tkg without the fshack patch. Would that be possible?

Thanks

**Comment by Kron4ek** [comment]
Hello,

It is possbile if you have the source code. You can specify the path to it in the `CUSTOM_SRC_PATH` variable. For example:

`export CUSTOM_SRC_PATH="/home/username/wine-tkg-nofshack-src"`

If you don't have the source code, you will need to get it from somewhere. For instance, you can generate it using the [wine-tkg](https://github.com/Frogging-Family/wine-tkg-git/tree/master/wine-tkg-git) build system. Or you can download it from [here](https://mega.nz/file/8E0G2S7R#2wTkmJKqrRU2hPGrR4uJST1lRQ6ZPbeZvpNsDJaOTeQ), generated it for you.
