### ISSUE TITLE
Wine tgk 7.0-rc1 AMD FSR missing

### ISSUE THREAD

**Issue by gabriele2000** [Kron4ek/Wine-Builds#52]
Title

**Comment by Kron4ek** [comment]
amd_fsr_fshack.mypatch causes compilation issues with latest Wine version, so i had to remove it for now. Actually, i initially thought that the compilation issues were because of the fullscreen hack, so i removed the whole fullscreen hack.

I will add FSR again when it is fixed.

**Comment by Kron4ek** [comment]
Added FSR to staging-tkg 7.0-rc2.
