### ISSUE TITLE
Error with "winemenubuilder.exe" in Linux Mint 19.3 with "wine-6.17-staging-tkg-amd64"

### ISSUE THREAD

**Issue by Patakreyp** [Kron4ek/Wine-Builds#53]
Every time I launch Guild Wars 2 with wine from your release "wine-6.17-staging-tkg-amd64" an error notice appears (see screenshot attached). I doesn't affect the functioning of Guild Wars 2, it's just annoying...

Linux distribution:
> $ cat /etc/os-release 
> NAME="Linux Mint"
> VERSION="19.3 (Tricia)"
> ID=linuxmint
> ID_LIKE=ubuntu
> PRETTY_NAME="Linux Mint 19.3"
> VERSION_ID="19.3"
> HOME_URL="https://www.linuxmint.com/"
> SUPPORT_URL="https://forums.linuxmint.com/"
> BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
> PRIVACY_POLICY_URL="https://www.linuxmint.com/"
> VERSION_CODENAME=tricia
> UBUNTU_CODENAME=bionic

Winetricks version (installed with Linux Min/Ubuntu package manager 'sudo apt install winetricks'):
> $ apt list winetricks
> Listing... Done
> winetricks/bionic,bionic,now 0.0+20180217-1 all [installed]
> 
> $ winetricks -V
> 20180217 - sha256sum: 1b156c616174f41df79d72a90c52eb2b110c63a6e8ecb865d303a8f9f0908924

The "script" I use to launch Guild Wars 2:
```bash
#!/bin/bash

WINEPREFIX=/home/pat/wine_for_gw2

WINE_CMD=/home/pat/wine-6.17-staging-tkg-amd64/bin/wine64

GW2_PATH=${WINEPREFIX}/drive_c/Program\ Files/Guild\ Wars\ 2
GW2_EXE_PATH=${GW2_PATH}/Gw2-64.exe

# Actual launch...
WINEPREFIX=${WINEPREFIX} WINEESYNC=1 WINEDEBUG=-all __GL_DEFAULT_LOG_ANISO=0 __GL_LOG_MAX_ANISO=0 __GL_FSAA_MODE=0 __GL_THREADED_OPTIMIZATIONS=1 __GL_SYNC_TO_VBLANK=0 __GL_YIELD=NOTHING LOGFILE=/dev/null ${WINE_CMD} "${GW2_EXE_PATH}"
```

Screenshot of error:
![Screenshot from 2021-12-27 18-33-23](https://user-images.githubusercontent.com/30236907/147494717-e1259126-85b4-49d8-85a2-7090755bba82.png)

Backtrace of error (from "Show Details" of error window):
[backtrace_20211227.txt](https://github.com/Tk-Glitch/wine-tkg/files/7781273/backtrace_20211227.txt)

**Comment by Kron4ek** [comment]
Winemenubuilder.exe is not present in my Wine builds, i disable it during compilation. Perhaps Guild Wars 2 tries to create some shortcuts on each run, hence the error.

You can disable `winedbg.exe` and the error window will not appear after that. Add to your script:

```
export WINEDLLOVERRIDES="winedbg.exe="
```

**Comment by Patakreyp** [comment]
Thanks for the workaround: no more error window ;o)
