### ISSUE TITLE
Warnings during vanilla Wine configuration

### ISSUE THREAD

**Issue by davidebeatrici** [Kron4ek/Wine-Builds#55]
```
configure: libcups 64-bit development files not found, CUPS won't be supported.
configure: libnetapi not found, Samba NetAPI won't be supported.
```

These would probably be solved by installing [`libcups2-dev`](https://packages.ubuntu.com/bionic/libcups2-dev) and [`samba-dev`](https://packages.ubuntu.com/bionic/samba-dev) (respectively) in the environment(s).

**Comment by Kron4ek** [comment]
You are right, installing `libcups2-dev` and `samda-dev` will remove these warnings. However, libcups2-dev conflicts with libjpeg62, so i can only add samba-dev (https://github.com/Kron4ek/Wine-Builds/commit/269005cf9ca0366a07c840a36732a23d546e825d).

**Comment by davidebeatrici** [comment]
Ah, that's unfortunate. No problem though, a single `configure` warning is an excellent result!
