### ISSUE TITLE
A request to add Wine-Proton to Heroic Games Launcher

### ISSUE THREAD

**Issue by Ahmed-E-86** [Kron4ek/Wine-Builds#57]
I opened a request to add your Wine-Proton builds to Heroic Games Launcher, but there are some issues implementing it. Could you please take a look at it -> https://github.com/Heroic-Games-Launcher/heroic-wine-downloader/issues/5

**Comment by Kron4ek** [comment]
Sorry, i don't know how can i help with that. Packing builds into separate archives is necessary since i provide three Wine flavors and two architectures. Creating a separate repository is kind of a solution, but i would prefer not to do this.

**Comment by Ahmed-E-86** [comment]
Alright. Fair enough.
