### ISSUE TITLE
Questions about improved-wine releases

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [Kron4ek/Wine-Builds#6]
I want to ask some questions about your improved-wine releases.

- Do your improved builds support **vkd3d**?
- There is 2 different hacks for Media Foundation that install native windows dlls. Can your **proton_mf_hacks.patch** replace these two hacks?!

**Comment by Kron4ek** [comment]
> Do your improved builds support vkd3d?

Yes, but not only the improved builds support vkd3d, all other builds support vkd3d too. However, you need to install vkd3d libraries into your system.

>  There is 2 different hacks for Media Foundation that install native windows dlls. Can your proton_mf_hacks.patch replace these two hacks?!

No, it doesn't eliminate the need to install native windows dlls, it's a small [patch](https://github.com/Tk-Glitch/PKGBUILDS/blob/master/wine-tkg-git/wine-tkg-patches/proton/proton_mf_hacks.patch) that fixes some functions

**Comment by ahmed-elsayed2017** [comment]
Thanks for your reply. Is there any external repository for vkd3d, or do I need to build it from source?

**Comment by Kron4ek** [comment]
I found [this](https://launchpad.net/~cybermax-dexter/+archive/ubuntu/vkd3d) PPA for Ubuntu 18.04, i haven't used it though. You can try it if you want.

**Comment by ahmed-elsayed2017** [comment]
> I found [this](https://launchpad.net/~cybermax-dexter/+archive/ubuntu/vkd3d) PPA for Ubuntu 18.04, i haven't used it though. You can try it if you want.

I will give it a try. Thanks.

**Comment by ahmed-elsayed2017** [comment]
Is **proton_mf_hacks.patch** included in your wine-proton builds?

**Comment by Kron4ek** [comment]
@ahmed-elsayed2017 Yes.

**Comment by ahmed-elsayed2017** [comment]
I am asking ,because someone mentioned that **proton_mf_hacks** only available in the unofficial proton builds only.

**Comment by Kron4ek** [comment]
Actually, it's available in the official Proton builds, [here](https://github.com/ValveSoftware/wine/commit/3b1cf8d88755a420b62e0d920bd4baa16cbcd0b0) is the commit in the Valve's repo.

I compile my Proton builds from the official sources, so they are fully identical to the official builds in regard to what patches are included.
