### ISSUE TITLE
Video playback broken in 7.3 and 7.4 [staging-tkg-amd64]

### ISSUE THREAD

**Issue by fallenguru** [Kron4ek/Wine-Builds#61]
Just a heads-up to let you know that 7.3 and 7.4 [staging-tkg-amd64] break video playback in a game I'm playing; the last known-good version is 7.2. Upstream [official WineHQ devel/staging builds for Ubuntu] is unaffected. It's probably a TKG issue, not one with this specific build, but I thought documenting it couldn't hurt.

**Comment by Kron4ek** [comment]
Thanks for the info. If video playback works with vanilla and staging, then yes, it is probably a regression in tkg.

**Comment by fallenguru** [comment]
Is something supposed to be fixed or is just an UPSTREAM, WONTFIX?

**Comment by Kron4ek** [comment]
It's an upstream and i can't fix this.
