### ISSUE TITLE
Is Fsr Activated?

### ISSUE THREAD

**Issue by artivision** [Kron4ek/Wine-Builds#62]
Any way to know if the Fsr on Staging-Tkg build is actually active when set?

**Comment by Kron4ek** [comment]
The only way is to compare the image quality. If i'm not sure FSR is active, i make two screenshots (with and without FSR) and compare them, but I usually can see the difference immediately.

If a game uses a proper fullscreen (not borderless window) and you chose a lower than native screen resolution, then FSR should be active.

**Comment by Kron4ek** [comment]
As far as i know, the only way is to compare the image quality. If i'm not sure FSR is active, i make two screenshots (with and without FSR) and compare them, but I usually can see the difference immediately.

If a game uses a proper fullscreen mode (not borderless window) and you chose a lower than native screen resolution, then FSR should be active.

**Comment by Kron4ek** [comment]
After examining the FSR patch, i found out that it there is another way to see if it is active or not, it leaves a trace in winedebug. You need to set `WINEDEBUG` to `trace+fshack` befure running a game:

```
export WINEDEBUG=trace+fshack
wine-7.4-staging-tkg-amd64/bin/wine game.exe
```

If FSR is active, you will see this such string among other strings:
```
022c:trace:fshack:fs_hack_is_fsr is_fsr: TRUE, sharpness: 0.2000
```

If it is not active, you will either this:
```
0230:trace:fshack:fs_hack_is_fsr is_fsr: FALSE, sharpness: 0.2000
```
Or there will be no FSR-related strings at all.
