### ISSUE TITLE
Question, not an issue.

### ISSUE THREAD

**Issue by MalonnBethesda** [Kron4ek/Wine-Builds#63]
I'm a Wine/Linux noob.  If I want a merged 32 and 64 bit Wine prefix that can run both 32 and 64 bit applications, what do I download?  The 32 bit build, or 64 bit build?  I am focused on a 32 bit game for this question, but there are things set up for 64 bit Windows (registry key backups, etc.)

So, I want to run a 32 bit game and 32 bit software, do I just download the 32 bit build?  Sounds dumb, but Windows and modern 64 bit OS's may be 64 bit, but support 32 bit.  I want that in Wine.  I have been compiling x86-x64 builds, but dependencies issues are preventing that now.

**Comment by Kron4ek** [comment]
> I'm a Wine/Linux noob. If I want a merged 32 and 64 bit Wine prefix that can run both 32 and 64 bit applications, what do I download? The 32 bit build, or 64 bit build?

In that case you need 64-bit builds, they can run both 32-bit and 64-bit apps. While 32-bit builds can only run 32-bit applications.

**Comment by MalonnBethesda** [comment]
Ok.  That is kinda what I thought, but wasn't sure.  Thanks for the quick response, @Kron4ek .
