### ISSUE TITLE
No internet access

### ISSUE THREAD

**Issue by MasterDevX** [Kron4ek/Wine-Builds#64]
I'm not sure if this repository is the right place to post this issue, but anyway. I've created a portable executable using scripts from [this repository](https://github.com/Kron4ek/wine-portable-executable). I've used [wine-7.5-staging-tkg-amd64.tar.xz](https://github.com/Kron4ek/Wine-Builds/releases/download/7.5/wine-7.5-staging-tkg-amd64.tar.xz) release from current repository. Everything works fine except internet connection. My apps that I run under wine are failing to connect to network. I've done some pings and it doesn't ping even to localhost. Any thoughts on this? Thanks!

```
Z:\home\user\Documents\wine>ping 1.1.1.1
Pinging 1.1.1.1 [1.1.1.1] with 32 bytes of data:
PING: transmit failed. General failure.
PING: transmit failed. General failure.
PING: transmit failed. General failure.
PING: transmit failed. General failure.

Ping statistics for 1.1.1.1
        Packets: Sent = 4, Received = 0, Lost = 4 (100% loss)

Z:\home\user\Documents\wine>ping 127.0.0.1
Pinging 127.0.0.1 [127.0.0.1] with 32 bytes of data:
PING: transmit failed. General failure.
PING: transmit failed. General failure.
PING: transmit failed. General failure.
PING: transmit failed. General failure.

Ping statistics for 127.0.0.1
        Packets: Sent = 4, Received = 0, Lost = 4 (100% loss)
```

**Comment by Kron4ek** [comment]
Does internet work if you run Wine in the regular way (without the portable-executable scripts)?

**Comment by MasterDevX** [comment]
> Does internet work if you run Wine in the regular way (without the portable-executable scripts)?

Nope. I have also tried to install wine from winehq repositories via apt, and internet is not working there too. Looks like some kind of config on my system is missing. I am running Debian Bullseye 11.2 with 5.10 kernel.

**Comment by Kron4ek** [comment]
Ping may not work in Wine, this is ok, i remember it required special permissions. Could you try Firefox (you can install it with winetricks)?

**Comment by MasterDevX** [comment]
> Could you try Firefox?

It works! I can browse all the websites with no problems.

The thing I'm trying to do is to install Microsoft Visual Studio 2019. I saw that wine 7.3 [changelog](https://www.winehq.org/announce/7.3) says it includes some patches for VS2019, so I decided I can try out my luck. The installer starts, but fails to download data.
![image](https://user-images.githubusercontent.com/32103950/161386548-44807ee6-4404-46e6-b375-631c6936b8b8.png)

**Comment by Kron4ek** [comment]
Ok, so internet work in Wine then, it is just that Visual Studio installer can't download files for some reason. Check if you have `libgnutls30` and `libgnutls30:i386` installed, these are important for some apps, maybe for the Visual Sudio installer too.

**Comment by MasterDevX** [comment]
> `libgnutls30` and `libgnutls30:i386`

Solved by installing these packages, thanks!

**Comment by melroy89** [comment]
For the users who might try to install Battle.net see also other potential missing packages (aside from `libgnutls30`) for your system: https://www.codeweavers.com/compatibility/crossover/tips/battlenet-desktop-app/required-install-these-system-libraries-first
