### ISSUE TITLE
winemenubuilder missing

### ISSUE THREAD

**Issue by MalonnBethesda** [Kron4ek/Wine-Builds#65]
WineMenuBuilder is missing from Wine 7.3 x64.  Does all of your builds leave WineMenuBuilder out?  I mean, some things (I'm trying winetricks now) won't launch without it.  I'm sure there's a slew of other things that won't work too, I just haven't tested yet because I need winetricks to install dependencies.

Is this an error, or do you know something I don't?

**Comment by MalonnBethesda** [comment]
I am trying Wine 7.2 x64.  It looks like winemenubuilder is not disabled in this build.  I'm trying to install .NET, and it appears it will launch outside of winetricks.  winetricks still won't launch, complaining about missing winemenubuilder.  I'm writing this before I test, but I searched and it seems Lutris disables winemenubuilder in their builds of Wine too.  They say it is harmless and it prevents something that is better off prevented.

I'll post back if I can get the app I want to run working in this prefix.

**Comment by MalonnBethesda** [comment]
Alright, I'll close this waste of space with this comment.  The app launches fine.  winemenubuilder is disabled by Lutris and is said to be harmless.  All is good, except winetricks won't run.  But I can live without winetricks.

Sorry to be useless.

**Comment by Kron4ek** [comment]
Yes, winemenubuilder is missing in all of my builds, but that shouln't break any applications. In the worst case some apps won't be able to create desktop shortcuts and that's all. Winetricks works fine without winemenubuilder.

**Comment by Kron4ek** [comment]
And regarding winetricks, do you get any errors (besides winemenubuilder.exe)?

**Comment by MalonnBethesda** [comment]
Nope, and that Wine couldn't find the application.  But it's there (unless there's a typo involved, but I'm 99.9% sure that's not the case).  So far all other apps (just use the build for 1) work fine.  Regedit, winecfg, etc.  It's not a big deal though.  I just installed application dependencies manually.
