### ISSUE TITLE
Wine tgk 7.7 - Fsr missing and fullscreen applications takes control of everything

### ISSUE THREAD

**Issue by gabriele2000** [Kron4ek/Wine-Builds#66]
If I open something that goes in fullscreen, black screen is a go and I cannot even terminate anything...

I have to restart the PC by switching to another session

**Comment by Kron4ek** [comment]
The wine-tkg repo has not been updated yet and fullscreen hack can't be applied to 7.7 at the moment, so i had to disable it. I will reupload the build, when the wine-tkg repo is updated.

**Comment by gabriele2000** [comment]
> The wine-tkg repo has not been updated yet and fullscreen hack can't be applied to 7.7 at the moment, so i had to disable it. I will reupload the build, when the wine-tkg repo is updated.

even if I disable FSR the issue is still here, that puzzles me.
You're saying that FSR and FSHack are connected but FSHack is the one that manages the fullscreen mode?

**Comment by Kron4ek** [comment]
> FSHack is the one that manages the fullscreen mode

Yes, fshack allows to change in-game fullscreen resolution without changing desktop resolution.

FSR is missing in 7.7 too, since it entirely depends on FShack, which is also not included.

**Comment by gabriele2000** [comment]
> > FSHack is the one that manages the fullscreen mode
> 
> Yes, fshack allows to change in-game fullscreen resolution without changing desktop resolution.
> 
> FSR is missing in 7.7 too, since it entirely depends on FShack, which is also not included.

Thanks a lot. Now that I think of, I run every game at half the resolution (for FSR), which is why every game killed my DE

**Comment by Kron4ek** [comment]
Reuploaded. Fshack and FSR are now included.
