### ISSUE TITLE
Mfplat unimplemented function, could be related to a past tkg issue?

### ISSUE THREAD

**Issue by gabriele2000** [Kron4ek/Wine-Builds#67]
See https://www.reddit.com/r/LinuxCrackSupport/comments/v5akx7/devil_may_cry_hd_collection_error_with_mfplat/

**Comment by Kron4ek** [comment]
Try regular Wine-Staging, if you get the sam error with then, then it's an upstream issue.

**Comment by gabriele2000** [comment]
> Try regular Wine-Staging, if you get the same error with it, then it's an upstream issue.

Basically now it displays something upside-down, but overall no crashes, I'm using wine's MF, not the native DLL
