### ISSUE TITLE
A request for unoffical Proton builds

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [Kron4ek/Wine-Builds#7]
Could you add the unofficial Proton builds, GE to you collection?

**Comment by Kron4ek** [comment]
I can't promise, but maybe i will add unofficial Proton builds with the same (or mostly the same) [set of patches](https://github.com/GloriousEggroll/proton-ge-custom/blob/proton-ge-4.21/game-patches-testing/proton-prep.sh) as in the GE builds.

**Comment by ahmed-elsayed2017** [comment]
Improved Proton builds. That will be great. Thanks.

**Comment by Kron4ek** [comment]
[Here](https://drive.google.com/open?id=1qpP0AJdT_lfBLKnq4-BbIzKLTiCgTbuS) is the Proton-Improved build that contains most of the patches from the latest GE build. Full list of the patches is in the txt file inside the build directory.

I decided to not publish it on the releases page yet as i’m still not sure that I will compile this kind of builds regularly. I will think about this for a while.

**Comment by ahmed-elsayed2017** [comment]
This build doesn't has the same issue that exists with your wine-staging, and wine-staging-improved builds.

The issue is that I can't use the keyboard/mouse, or my joystick with certain games like DMC5, and Blacksad. This issue doesn't exist with your proton builds.

There are some patches that exist with Proton, and don't exist with wine, and I don't think that all of these patches will be merged to wine, that is why wine builds that contains all of proton patches that didn't merge to wine are so important.

**Comment by ahmed-elsayed2017** [comment]
Also, when pressing alt + tab to go to the desktop, then using alt + tab to go back to the game again, I can't use the controller anymore, I can use only mouse + keyboard. This issue doesn't happen with Proton, and Proton GE.

**Comment by Kron4ek** [comment]
Does [this](https://drive.google.com/open?id=1LY7Dchq4b_HDbAxY8EBI1Ffk0ASkvZ6t) build works fine for you? I mean in regard to problems you mentioned above.

**Comment by ahmed-elsayed2017** [comment]
> Does [this](https://drive.google.com/open?id=1LY7Dchq4b_HDbAxY8EBI1Ffk0ASkvZ6t) new build works fine for you? I mean in regard to the problems you mentioned above.

So far, so good. What are the patches did you add? I want to add these patched to my bug report to see if they are willing to add them to WINE.

**Comment by Kron4ek** [comment]
Good.

> What are the patches did you add?

I added three patches (from TkG repo) that contain some changes from Proton regarding SDL/gamepads: [this](https://github.com/Tk-Glitch/PKGBUILDS/blob/master/wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-gamepad-additions.patch), [this](https://github.com/Tk-Glitch/PKGBUILDS/blob/master/wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-sdl-joy.patch) and [this](https://github.com/Tk-Glitch/PKGBUILDS/blob/master/wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-sdl-joy-2.patch).

**Comment by ahmed-elsayed2017** [comment]
Thanks for your help.

**Comment by Kron4ek** [comment]
I will probably add these patches to my improved 5.0-rc3 build.

**Comment by ahmed-elsayed2017** [comment]
> I will probably add these patches to my improved 5.0-rc3 build.

That will be great. I don't know if WINE developers will ever add these patches. They may end as Proton only patches like proton-fullscreen-hack
