### ISSUE TITLE
Change "amd_fsr_fshack.mypatch" to "amd_fsr_fshack-alternative.mypatch"

### ISSUE THREAD

**Issue by gabriele2000** [Kron4ek/Wine-Builds#73]
It better reflects the improvements made by Proton GE and may be useful for some stubborn games that refuses to have a true fullscreen, even if they say so (BioShock 1 Remastered for example).

If you'd like, would you kindly generate the 7.18 build with that change?

[Patch](https://github.com/Frogging-Family/community-patches/blob/49f20a1781bdba3afff65cec6e80df4333ca01d0/wine-tkg-git/amd_fsr_fshack-alternative.mypatch)

EDIT: I'd've done it myself if I didn't have Pop!_Os as OS, since it's an Ubuntu-based OS and it clashes with multilib compiling.

**Comment by Kron4ek** [comment]
[Here](https://mega.nz/file/VQFjhTqI#PyJIEVfC_MmgPuSJ-IeTt0aVlv1dJ3Jmmbi4bFu58C0) it is.

**Comment by gabriele2000** [comment]
> [Here](https://mega.nz/file/VQFjhTqI#PyJIEVfC_MmgPuSJ-IeTt0aVlv1dJ3Jmmbi4bFu58C0) it is.

Nice! Thanks!
Do you think it would be good if you'd used that patch from now on, or would that lead to some problems?

**Comment by Kron4ek** [comment]
I will include it in 7.19. I think it there will be no problems, but we will see.

**Comment by gabriele2000** [comment]
> I will include it in 7.19. I think it there will be no problems, but we will see.

Thanks a lot!
