### ISSUE TITLE
Please update wine 8

### ISSUE THREAD

**Issue by ajay9634** [Kron4ek/Wine-Builds#75]
I am using your wine in my exagear bb, please update wine 8,thanks

**Comment by gabriele2000** [comment]
> I am using your wine in my exagear bb, please update wine 8,thanks

Maybe this is not the reply you were looking for but I have a few thoughts about it:
- He's not updating wine (yet) because there are two or three important patches that are broken and needs to be refactored
- He's waiting directly until wine 8 which will come in January

**Comment by Kron4ek** [comment]
Done.

**Comment by gabriele2000** [comment]
> Done.

is fshack and FSR here or the patches are still broken?

**Comment by Kron4ek** [comment]
They are still broken.

**Comment by ajay9634** [comment]
I tried different wines,
Wine 4 ,6 are fast but 7,8 is slow, I don't know why but improved compatibility.
I hope some day it will faster than wine4

**Comment by ajay9634** [comment]
[images.jpeg](https://user-images.githubusercontent.com/78233144/209457458-7d55098f-47e3-40c1-a2d8-f7b1f4ea160d.jpeg)

**Comment by ajay9634** [comment]
Now wine 8 stable released, please upload it

**Comment by ajay9634** [comment]
Wine 8.2 released
