### ISSUE TITLE
The .tar.xz are not generated

### ISSUE THREAD

**Issue by MrPurple666** [Kron4ek/Wine-Builds#77]
Hey, I'm trying to build wine with the scripts (no errors so far) but nothing is generated. I have all dependencies installed as well as tried using even issue #76  chroot ready-to-use and nothing is generated even without errors; looking at the chroots in opt/ after the "build" of wine there are no files related to wine. Is there any way to help me build?

**Comment by Kron4ek** [comment]
Hi, remove all lines containing `clear` from build_wine.sh, run it and show me its output.

**Comment by MrPurple666** [comment]
Full log output:
[terminal_output.txt](https://github.com/Kron4ek/Wine-Builds/files/10378592/terminal_output.txt)

**Comment by MrPurple666** [comment]
> Hi, remove all lines containing `clear` from `build_wine.sh`, run it and show me its output.

Full terminal output:
[terminal_log.txt](https://github.com/Kron4ek/Wine-Builds/files/10379055/terminal_log.txt)

**Comment by Kron4ek** [comment]
Did you run the script as root? And if so, could you try without root rights? Also, what Linux dsitro are you using?

**Comment by MrPurple666** [comment]
> Did you run the script as root? And if so, could you try without root rights? Also, what Linux dsitro are you using?
> 
> And please show me the output of:
> 
> ```
> $ ls -l /proc/sys/kernel/overflowuid
> $ cat /proc/sys/kernel/overflowuid
> $ bwrap --version
> ```

I tried it with and without root access, both gave the same result; my distro is an ubuntu proot-distro (aarch64)
the output:

```
root@localhost:~# ls -l /proc/sys/kernel/overflowuid
ls: cannot access '/proc/sys/kernel/overflowuid': Permission denied
root@localhost:~# cat /proc/sys/kernel/overflowuid
cat: /proc/sys/kernel/overflowuid: Permission denied
root@localhost:~# bwrap --version
bubblewrap 0.7.0
```
Maybe it's some incompatibility with proot-distro's or aarch64?

**Comment by Kron4ek** [comment]
> Maybe it's some incompatibility with proot-distro's or aarch64?

Yes, proot is probably the reason. Anyway, even with working bwrap, you won't be able to compile x86 Wine in x86 chroots on aarch64, unless you are using an emulator.

**Comment by MrPurple666** [comment]
> > Maybe it's some incompatibility with proot-distro's or aarch64?
> 
> Yes, proot is probably the reason. Anyway, even with working bwrap, you won't be able to compile x86 Wine in x86 chroots on aarch64, unless you are using an emulator.

Oh, Thank you very much :)
