### ISSUE TITLE
Winegcc

### ISSUE THREAD

**Issue by osxmidi** [Kron4ek/Wine-Builds#78]
Is there any reason why these tkg builds have a winegcc that requires clang?

All of the other winegcc's I've used in other Wine's are using g++.

The problem is that the current clang on Arch based systems is not producing tkg's winegcc made binaries that run whereas g++ and WineHQ's winegcc is.

It's the same for the 64 bit Wine and the 64 bit Wine-staging-tkg on the releases page.

I don't know if it's just Arch issue as I havn't tested other distros clang's with wine-tkg's winegcc.

**Comment by Kron4ek** [comment]
I think it's because i use gcc-9 to compile my Wine builds and it becomes the default for winegcc. So as a workaround you can symlink gcc to gcc-9:

```
sudo ln -s /usr/bin/gcc /usr/bin/gcc-9
```

**Comment by osxmidi** [comment]
Maybe it's a configuration option that could be changed as all Wine console based apps won't build properly and maybe other apps.

If I find anything out about the configuration I'll post it.

**Comment by osxmidi** [comment]
> I think it's because i use gcc-9 to compile my Wine builds and it becomes the default for winegcc. And since there is no gcc-9 in Arch, it tries to use clang instead. As a workaround you can symlink gcc to gcc-9:
> 
> ```
> $ sudo ln -s /usr/bin/gcc /usr/bin/gcc-9
> ```

Thanks, I'll try that and see how it goes.

**Comment by osxmidi** [comment]
> I think it's because i use gcc-9 to compile my Wine builds and it becomes the default for winegcc. And since there is no gcc-9 in Arch, it tries to use clang instead. As a workaround you can symlink gcc to gcc-9:
> 
> ```
> $ sudo ln -s /usr/bin/gcc /usr/bin/gcc-9
> ```

I tried it out and it works.

Thanks.
