### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by lucasmz1** [Kron4ek/Wine-Builds#79]
How do I run 32 bit apps in wine 64 bits?

**Comment by lucasmz1** [comment]
lucas[bin]$ ./wine ~/Downloads/Defraggler/Defraggler.exe 
bash: ./wine: Arquivo ou diretório inexistente
lucas[bin]$ ./wine64 ~/Downloads/Defraggler/Defraggler.exe 
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
002c:err:winediag:getaddrinfo Failed to resolve your host name IP
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
wine: failed to open L"C:\\windows\\system32\\winemenubuilder.exe": c0000135
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 00010000-00110000
/lib/ld-linux.so.2: could not open
O aplicativo não pôde ser iniciado ou não existe aplicativo associado ao arquivo
 especificado.
ShellExecuteEx falhou: Erro interno.

**Comment by lucasmz1** [comment]
It didn't work ? here I'm trying to run defraggler 32 bit with wine64 but it won't run.

**Comment by Kron4ek** [comment]
Well, you need to install 32-bit dependecines in your system. At least 32-bit glibc (libc6), 32-bit fontconfig, 32-bit opengl driver.

**Comment by lucasmz1** [comment]
ok It make everything clear. thank you.
