### ISSUE TITLE
Help wanted about GPU driver 

### ISSUE THREAD

**Issue by Saikatsaha1996** [Kron4ek/Wine-Builds#81]
My GPU not recognised
I am using vanilla 8.0 rc2
![Screenshot_2023-01-20-14-28-07-147_com gaurav avnc](https://user-images.githubusercontent.com/72664192/213675859-bc9b5625-3bfe-40ba-9b56-930a0d03ec5e.jpg)

**Comment by Kron4ek** [comment]
If your distro is 64-bit, make sure you also have 32-bit opengl driver installed.

**Comment by Saikatsaha1996** [comment]
> If your distro is 64-bit, make sure you also have 32-bit opengl driver installed.

Okay but i am using 32 bit & 64 bit wine..

And in this picture i am using 64 bit wine

**Comment by Kron4ek** [comment]
Ok, but do you have 32-bit panfrost opengl driver installed? Geek3D GPU Caps Viewer is a 32-bit program and Wine uses 32-bit drivers for 32-bit applications, so it's important to have them installed.

**Comment by Saikatsaha1996** [comment]
> Ok, but do you have 32-bit panfrost opengl driver installed? Geek3D GPU Caps Viewer is a 32-bit program and Wine uses 32-bit drivers for 32-bit applications, so it's important to have them installed.

No i installed 64 bit GPU caps viewer

**Comment by Kron4ek** [comment]
Where did you get it? On the official site i can only find the 32-bit version.

**Comment by Saikatsaha1996** [comment]
> Where did you get it? On the official site i can only find the 32-bit version.

https://gpu-caps-viewer.en.lo4d.com/windows

**Comment by Kron4ek** [comment]
It's a 32-bit version.
```
$ file GPU_Caps_Viewer.exe
GPU_Caps_Viewer.exe: PE32 executable (GUI) Intel 80386, for MS Windows, 5 sections
```

**Comment by Saikatsaha1996** [comment]
> It's a 32-bit version.
> 
> ```
> $ file GPU_Caps_Viewer.exe
> GPU_Caps_Viewer.exe: PE32 executable (GUI) Intel 80386, for MS Windows, 5 sections
> ```

Okay.. so i need to build mesa 32bit driver also..
I am not much familiar with cross compile.. if you can just tell me is it okay?

```
[binaries]
c='gcc'
cpp='g++'
ar='ar'
strip='strip'
pkgconfig='arm-linux-gnueabihf-pkg-config'
#llvm-config='/usr/bin/llvm-config-32'

[properties]
c_args=['-marm', '-mfpu=neon']
c_link_args=['-marm']
cpp_args=['-marm', '-mfpu=neon']
cpp_link_args=['-marm']

[host_machine]
system='linux64'
cpu_family='aarch64'
cpu='aarch64'

[target_machine]
system='linux32'
cpu_family='arm'
cpu='arm'
```

**Comment by Kron4ek** [comment]
Sorry, i can't tell, i'm not very familiar with cross compile either, especially on ARM.

**Comment by Saikatsaha1996** [comment]
> Sorry, i can't tell, i'm not very familiar with cross compile either, especially on ARM.

But oky thank you for your help

**Comment by Kron4ek** [comment]
Let me know if Geeks3D recognizes your GPU after building and installing the 32-bit driver.

**Comment by Saikatsaha1996** [comment]
> Let me know if Geeks3D recognizes your GPU after building and installing the 32-bit driver.

Yes i will update after install

**Comment by Saikatsaha1996** [comment]
> Let me know if Geeks3D recognizes your GPU after building and installing the 32-bit driver.

Solved thank you
Vanilla version 8.0 rc2
![Screenshot_2023-01-20-20-36-56-838_com gaurav avnc](https://user-images.githubusercontent.com/72664192/213731458-5fb6b88b-baf5-4065-b69d-8b128d3cd2ed.jpg)

**Comment by Kron4ek** [comment]
Good :)

**Comment by Saikatsaha1996** [comment]
> Good :)

You have good experience can you just help me with an answer?

I actually never used wine 🍷 .. that's why asking..
What is dynamic dll overide? And it is mandatory to override all dlls files ?.. how can I know which dll i should overide?
Please it will very helpful for me.. 

Thank you

**Comment by Saikatsaha1996** [comment]
Can't run a single game..
Wine stag-tkg 8.0-rc2 x86_64 
box86 & box64
Euro truck simulator 2 installation crashed
![Screenshot_2023-01-22-14-19-23-577_com gaurav avnc](https://user-images.githubusercontent.com/72664192/213907699-a4bbf458-4c67-4d57-ba04-7ac32c81f5e2.jpg)

Openrail 1.2 & 1.5 installed successfully.. but can't run..
![Screenshot_2023-01-22-11-18-17-628_com gaurav avnc](https://user-images.githubusercontent.com/72664192/213907749-0fdb9839-121b-4b7c-a32a-0af591a220f4.jpg)

**Comment by Kron4ek** [comment]
> What is dynamic dll overide?

DLL overrides allow to control what dll Wine should use - builtin or external ("native" according to Wine terminology). For example, Wine has builtin ddraw.dll and uses it by default, some games ship their own ddraw.dll and in order to force Wine to use it instead of the builtin one we can use `WINEDLLOVERRIDES` (or do this via winecfg):
```
WINEDLLOVERRIDES="ddraw=n,b"
```
"n,b" here means "use native dll and if it's not found, then use builtin.

Same can be done to other dlls like d3dx9_43, d3dcompiler_43, etc...

> And it is mandatory to override all dlls files ?

All dlls? Definitely not. But sometimes it's required to install and/or override some dlls to make an application work.

> how can I know which dll i should overide?

Sometimes Wine shows errors or warnings that hint on what dlls need to be installed and overriden. For example, if there are d3dx related errors, then installing d3dx9 libraries might help.

**Comment by Kron4ek** [comment]
> ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory

Try to load the snd-seq module.

```
# modprobe snd-seq
```
> Euro truck simulator 2 installation crashed

Try a different installer or, even better, download an already installed/extracted game.

> Openrail 1.2 & 1.5 installed successfully.. but can't run..

Unfortunately, i don't know how to fix this.

**Comment by Saikatsaha1996** [comment]
> > ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
> 
> Try to load the snd-seq module.
> 
> ```
> # modprobe snd-seq
> ```
> 
> > Euro truck simulator 2 installation crashed
> 
> Try a different installer or, even better, download an already installed/extracted game.
> 
> > Openrail 1.2 & 1.5 installed successfully.. but can't run..
> 
> Unfortunately, i don't know how to fix this.

Actually i am not rooted i am using box64 & box86 
My DirectX not working because alsalib problem..
I already have pulse audio enabled in termux..

I checked all your version.. version vanilla, STG+tkg, STG all version Same problem..

![Screenshot_2023-01-22-16-32-16-716_com gaurav avnc](https://user-images.githubusercontent.com/72664192/213939055-59eeb04e-60ff-4409-a7c9-ef67669a1bb9.jpg)

**Comment by Kron4ek** [comment]
Does sound work at all? For example, in winecfg or in other applications?

**Comment by Saikatsaha1996** [comment]
> Does sound work at all? For example, in winecfg or in other (native) application

How do I checked sound working or not in wine ?

**Comment by Kron4ek** [comment]
In winecfg there is "Test Sound" button on the Audio tab.

**Comment by Saikatsaha1996** [comment]
> In winecfg there is "Test Sound" button on the Audio tab.

Yes working in winecfg

**Comment by Saikatsaha1996** [comment]
> In winecfg there is "Test Sound" button on the Audio tab.

See i am trying to run `dxdiag.exc`
Getting error

```
013c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
013c:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x30
013c:fixme:wbemprox:enum_class_object_Next timeout not supported
013c:fixme:d3d:wined3d_guess_card No card selector available for card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 13.0.1, 128 bits)").
013c:fixme:d3d:wined3d_guess_card No card selector available for card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 13.0.1, 128 bits)").
013c:fixme:ddraw:ddraw7_Initialize Ignoring guid {aeb2cdd4-6e41-43ea-941c-8361cc760781}.
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
013c:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
013c:fixme:dxdiag:wWinMain Information dialog is not implemented

```
Wine test sound working fine..
In proot sound working fine..

**Comment by Kron4ek** [comment]
Check if you have these packages installed:
```
libasound2-plugins libasound2-plugins:i386
```

> ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
> 013c:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.

I don't think this is a critical error that prevents your application from working.

**Comment by Saikatsaha1996** [comment]
> 

Yes 32 bit & 64 bit `libasound2-plugins` available..

**Comment by Kron4ek** [comment]
Well, i don't know, box86/box64 may have its own issues i guess. As for ETS2, there is a native Linux version, you can try to run it with box64.

**Comment by Saikatsaha1996** [comment]
> Well, i don't know, box86/box64 may have its own issues i guess. As for ETS2, there is a native Linux version, you can try to run it with box64.

Check video i included in last reply.. i am using now 32 bit version all.. wine 32 bit, game 32bit also..

**Comment by Kron4ek** [comment]
I see, but i don't know how to help you with that, unfortunately.

**Comment by Saikatsaha1996** [comment]
> I see, but i don't know how to help you with that, unfortunately.

Error code!
```
up installs Euro Truck Simulator 2 on your computer."): stub
0144:fixme:msg:ChangeWindowMessageFilterEx 000200EE c057 1 00000000
0144:fixme:msg:ChangeWindowMessageFilterEx 000200F6 c057 1 00000000
0144:fixme:msg:ChangeWindowMessageFilterEx 000300F6 c057 1 00000000
0144:fixme:shell:SHAutoComplete stub
0144:fixme:msg:ChangeWindowMessageFilterEx 000400F6 c057 1 00000000
0144:fixme:gdiplus:resample_bitmap_pixel Unimplemented interpolation 6
0164:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
wine: Unhandled page fault on read access to 12431AFC at address 124310A2 (thread 0178), starting debugger...
```

**Comment by Saikatsaha1996** [comment]
> I see, but i don't know how to help you with that, unfortunately.

I guess it is sound issue..or anything missing in regedit

```
0100:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
```

**Comment by Saikatsaha1996** [comment]
Dear i think it will solve but need this .so flle for aarch64-linux-gnu

Can you share any idea please?

https://github.com/akbarri/ExaGear-SoundFix

**Comment by Kron4ek** [comment]
> Dear i think it will solve but need this .so flle for aarch64-linux-gnu
> Can you share any idea please?
> https://github.com/akbarri/ExaGear-SoundFix

ExaGear is a different emulation software, i don't think think will solve your issue with sound, since you are using box86/box64 and not ExaGear.

> ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory

You need to load snd-seq module to fix this issue. If your kernel is compiled with `CONFIG_SND_SEQUENCER=m`, you can load the module by executing `modprobe snd-seq` as root on your device out of the proot environment.

But I don't really think that the absence of `/dev/snd/seq` is the real problem that prevents applications from working, the real problem is probably elsewhere. Anyway, i'm not an expert in emulation.

**Comment by Saikatsaha1996** [comment]
> > Dear i think it will solve but need this .so flle for aarch64-linux-gnu
> > Can you share any idea please?
> > https://github.com/akbarri/ExaGear-SoundFix
> 
> ExaGear is a different emulation software, i don't think think will solve your issue with sound, since you are using box86/box64 and not ExaGear.
> 
> > ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
> 
> You need to load snd-seq module to fix this issue. If your kernel is compiled with `CONFIG_SND_SEQUENCER=m`, you can load the module by executing `modprobe snd-seq` as root on your device out of the proot environment.
> 
> But I don't really think that the absence of  is the real problem that prevents applications from working, the real problem is probably elsewhere. Anyway, i'm not an expert in emulation.

Actually i am not rooted.. 2nd i don't have any permission to access `/dev/snd/seq` 

Not a single version wine working.. i really i Start `dxdiag` now i am fully mad.. i can't explain you about situation.. because i can't recognise the issues..

**Comment by Saikatsaha1996** [comment]
> > Dear i think it will solve but need this .so flle for aarch64-linux-gnu
> > Can you share any idea please?
> > https://github.com/akbarri/ExaGear-SoundFix
> 
> ExaGear is a different emulation software, i don't think think will solve your issue with sound, since you are using box86/box64 and not ExaGear.
> 
> > ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
> 
> You need to load snd-seq module to fix this issue. If your kernel is compiled with `CONFIG_SND_SEQUENCER=m`, you can load the module by executing `modprobe snd-seq` as root on your device out of the proot environment.
> 
> But I don't really think that the absence of `/dev/snd/seq` is the real problem that prevents applications from working, the real problem is probably elsewhere. Anyway, i'm not an expert in emulation.

See dear same problem with me
`https://github.com/CypherpunkArmory/UserLAnd/issues/135#issuecomment-410138921`

Can you please share all dependency list for wine 32 bit ?..

Than i will complete for testing without audio.. 
Or 
If you have time can you compile & share full sound disable with directx sound also in a zip ?

**Comment by Kron4ek** [comment]
You can see all dependencies [here](https://packages.ubuntu.com/lunar/libwine).

**Comment by Saikatsaha1996** [comment]
> You can see all dependencies [here](https://packages.ubuntu.com/lunar/libwine).

Okay thank you

**Comment by Saikatsaha1996** [comment]
> You can see all dependencies [here](https://packages.ubuntu.com/lunar/libwine).

If you don't mind can you guide me please what mistake i done ?
I just complied without any sound now received this error on fast startup

```
ubuntu@localhost:~$ box86 wine wineboot
Box86 with Dynarec v0.2.9 ada65fc0 built on Jan 23 2023 06:30:40
Error: Symbol __gmtime64 not found, cannot apply R_386_JMP_SLOT 0xf71ad010 (0x6056) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __localtime64 not found, cannot apply R_386_JMP_SLOT 0xf71ad01c (0x6086) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __stat64_time64 not found, cannot apply R_386_JMP_SLOT 0xf71ad030 (0x60d6) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __fstatat64_time64 not found, cannot apply R_386_JMP_SLOT 0xf71ad040 (0x6116) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __recvmsg64 not found, cannot apply R_386_JMP_SLOT 0xf71ad068 (0x61b6) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __futimens64 not found, cannot apply R_386_JMP_SLOT 0xf71ad08c (0x6246) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __getsockopt64 not found, cannot apply R_386_JMP_SLOT 0xf71ad0b0 (0x62d6) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __sendmsg64 not found, cannot apply R_386_JMP_SLOT 0xf71ad0cc (0x6346) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __fstat64_time64 not found, cannot apply R_386_JMP_SLOT 0xf71ad0e8 (0x63b6) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __clock_getres64 not found, cannot apply R_386_JMP_SLOT 0xf71ad0ec (0x63c6) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __setsockopt64 not found, cannot apply R_386_JMP_SLOT 0xf71ad138 (0x64f6) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __select64 not found, cannot apply R_386_JMP_SLOT 0xf71ad140 (0x6516) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __fcntl_time64 not found, cannot apply R_386_JMP_SLOT 0xf71ad148 (0x6536) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __lstat64_time64 not found, cannot apply R_386_JMP_SLOT 0xf71ad200 (0x6816) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __ctime64 not found, cannot apply R_386_JMP_SLOT 0xf71ad210 (0x6856) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __gettimeofday64 not found, cannot apply R_386_JMP_SLOT 0xf71ad244 (0x6926) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __ioctl_time64 not found, cannot apply R_386_JMP_SLOT 0xf71ad278 (0x69f6) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __mktime64 not found, cannot apply R_386_JMP_SLOT 0xf71ad298 (0x6a76) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __time64 not found, cannot apply R_386_JMP_SLOT 0xf71ad2cc (0x6b46) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Box86 with Dynarec v0.2.9 ada65fc0 built on Jan 23 2023 06:30:40
Error: Symbol __gmtime64 not found, cannot apply R_386_JMP_SLOT 0xe9e2d010 (0x6056) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __localtime64 not found, cannot apply R_386_JMP_SLOT 0xe9e2d01c (0x6086) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __stat64_time64 not found, cannot apply R_386_JMP_SLOT 0xe9e2d030 (0x60d6) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __fstatat64_time64 not found, cannot apply R_386_JMP_SLOT 0xe9e2d040 (0x6116) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __recvmsg64 not found, cannot apply R_386_JMP_SLOT 0xe9e2d068 (0x61b6) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __futimens64 not found, cannot apply R_386_JMP_SLOT 0xe9e2d08c (0x6246) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __getsockopt64 not found, cannot apply R_386_JMP_SLOT 0xe9e2d0b0 (0x62d6) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __sendmsg64 not found, cannot apply R_386_JMP_SLOT 0xe9e2d0cc (0x6346) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __fstat64_time64 not found, cannot apply R_386_JMP_SLOT 0xe9e2d0e8 (0x63b6) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __clock_getres64 not found, cannot apply R_386_JMP_SLOT 0xe9e2d0ec (0x63c6) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __setsockopt64 not found, cannot apply R_386_JMP_SLOT 0xe9e2d138 (0x64f6) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __select64 not found, cannot apply R_386_JMP_SLOT 0xe9e2d140 (0x6516) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __fcntl_time64 not found, cannot apply R_386_JMP_SLOT 0xe9e2d148 (0x6536) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __lstat64_time64 not found, cannot apply R_386_JMP_SLOT 0xe9e2d200 (0x6816) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __ctime64 not found, cannot apply R_386_JMP_SLOT 0xe9e2d210 (0x6856) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __gettimeofday64 not found, cannot apply R_386_JMP_SLOT 0xe9e2d244 (0x6926) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __ioctl_time64 not found, cannot apply R_386_JMP_SLOT 0xe9e2d278 (0x69f6) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __mktime64 not found, cannot apply R_386_JMP_SLOT 0xe9e2d298 (0x6a76) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol __time64 not found, cannot apply R_386_JMP_SLOT 0xe9e2d2cc (0x6b46) in /home/ubuntu/wine-i386/bin/../lib/wine/i386-unix/ntdll.so
ubuntu@localhost:~
``|

**Comment by Saikatsaha1996** [comment]
> You can see all dependencies [here](https://packages.ubuntu.com/lunar/libwine).

Dear i hope you have full setup.. i don't know mey be i done something wrong so i can't start my own build wine.. i believe you already have full setup for wine build environment.. can you please share without sound support? Please? I am sure wine will work if sound is disabled..

Also if you don't have time for compile without sound support please notify me once..

Thank you 

https://www.reddit.com/r/wine_gaming/comments/o4wjk8/wine_error_unhandled_page_fault_on_read_access/

Same error

**Comment by Kron4ek** [comment]
[Here](https://drive.google.com/drive/folders/1gI7XoRKZ7CCYxpXhTXdQIHblXa-H7yzp) is a build with audio support disabled.

**Comment by Saikatsaha1996** [comment]
> [Here](https://drive.google.com/drive/folders/1gI7XoRKZ7CCYxpXhTXdQIHblXa-H7yzp) is a build with audio support disabled.

🙏 Thank you so much for your help 🥰
