### ISSUE TITLE
.net 4.8 work?

### ISSUE THREAD

**Issue by jackbingow** [Kron4ek/Wine-Builds#82]
.net 4.8 work?
Have Mono installed.
camera tool otis_inf refuses to run ubuntu via wine 7.0.

**Comment by Kron4ek** [comment]
Camera tool by otis_inf does not work even with Wine 8.0 and Mono 7.4.0. You can try to install Net Framework 4.8 via winetricks:

```
$ winetricks dotnet48
```

**Comment by jackbingow** [comment]
@Kron4ek 
I am talking about this:
[https://opm.fransbouma.com/Cameras/uncharted4.htm](https://opm.fransbouma.com/Cameras/uncharted4.htm)
Google  filename UnchartedLoTC_tools_v101.zip and gives 1 result(source)
On Windows 7 VM with net framework 4.5.2 camera tool work, but game Uncharted 4 PC won't.
tried launching on lutris and via proton command line give xml exception error in terminal.
tried installing dotnet via
`wine `

**Comment by Kron4ek** [comment]
Net Framework 4.5.2 installs without issues with Wine-Staging 8.0, i installed it with winetricks:
```
$ winetricks -q dotnet452
```

After installing dotnet452 and setting Windows version to "Windows 7" in winecfg i got the program working. I mean the graphical interface works, but i don't know if injection does work or not.

![otis](https://user-images.githubusercontent.com/13851877/215049405-ce011d1b-fd5a-4831-9016-d5775f953600.png)
