### ISSUE TITLE
Build proton-wine-7.0-6d

### ISSUE THREAD

**Issue by liberodark** [Kron4ek/Wine-Builds#83]
Hi, 

Can you do a build ? from this tag [proton-wine-7.0-6d](https://github.com/ValveSoftware/wine/releases/tag/proton-wine-7.0-6d)

Best Regards & Happy New Year

**Comment by Kron4ek** [comment]
Hi,

[Here](https://mega.nz/folder/JNFUjZoQ#q-AFjDhb2f38n371OP2LwA) it is. I won't upload it on the releases page though, because i'm waiting for a proper 7.0-6 release.

**Comment by liberodark** [comment]
I understand thank you
