### ISSUE TITLE
There is a problem using box86 in the proot container

### ISSUE THREAD

**Issue by 1361217459** [Kron4ek/Wine-Builds#84]
![Uploading Screenshot_2023-02-05-22-57-21-719_com.realvnc.viewer.android.jpg…]()

**Comment by 1361217459** [comment]
Box86 with Dynarec v0.2.9 27756113 built on Feb  5 2023 14:08:09
Box86 with Dynarec v0.2.9 27756113 built on Feb  5 2023 14:08:09
Box86 with Dynarec v0.2.9 27756113 built on Feb  5 2023 14:08:09
wineserver: using server-side synchronization.
wine client error:0: recvmsg: Connection reset by peer

**Comment by Kron4ek** [comment]
Sorry, i don't know how to help you with this issue. Try older Wine versions, maybe some of them will work.

**Comment by 1361217459** [comment]
thank u,i wil close issue later
