### ISSUE TITLE
Update Wine Wayland (Collabora) build

### ISSUE THREAD

**Issue by jmacato** [Kron4ek/Wine-Builds#85]
Seems like it's been too long since the wayland-collabora binary has been updated. There has been many latest changes to https://gitlab.collabora.com/alf/wine/-/tree/wayland and it'd be great if we get to have another build of this up here :)

**Comment by Kron4ek** [comment]
Unfortunately, i can't compile it on Ubuntu 18.04 (and even on Ubuntu 20.04), because it requires newer libwayland than available there. Two years ago it compiled fine, but no longer. I can probably compile it on Ubuntu 22.04, but it will require glibc 2.35 then and won't run on older distros.

**Comment by Etaash-mathamsetty** [comment]
> Unfortunately, i can't compile it on Ubuntu 18.04 (and even on Ubuntu 20.04), because it requires newer libwayland than available there. Two years ago it compiled fine, but no longer. I can probably compile it on Ubuntu 22.04, but it will require glibc 2.35 then and won't run on older distros.

what's wrong with that? Wayland and gaming in general won't work that well on older distros anyways

**Comment by Kron4ek** [comment]
> what's wrong with that? Wayland and gaming in general won't work that well on older distros anyways
you do have a point with something like debian stable though

Nothing wrong actually. I just tried to compile it on Ubuntu 22.04 and still it gives me an error during configure:

```
Wayland 64-bit development files not found or not new enough, the Wayland driver won't be supported.
This is an error since --with-wayland was requested.
```

Even though i have `libwayland-dev` and `libwayland-egl-backend-dev` installed, and i doubt that libwayland 1.20 is not new enough. Don't know how to fix this. It does not give this error on Arch Linux though.
