### ISSUE TITLE
Please add winemenubuilder.exe and winemenubuilder.exe.so in wine

### ISSUE THREAD

**Issue by ajay9634** [Kron4ek/Wine-Builds#89]
I know some files are missing from your build but please add these files

- winemenubuilder.exe -winemenubuilder.exe.so

Thanks, I like your wine

**Comment by Kron4ek** [comment]
Sorry, but I won't add. I removed winemenubuilder because it pollutes mime types and applications menus on prefix update and I find this annoying.

**Comment by Kron4ek** [comment]
If you really need winemenubuilder, you can take it from other Wine builds that include it. Just copy winemenubuilder.exe and winemenubuilder.exe.so to proper locations and it should work.
