### ISSUE TITLE
Raw input in 5.0rc2 improved staging amd64 makes guild wars 2 unplayable

### ISSUE THREAD

**Issue by Mel34** [Kron4ek/Wine-Builds#9]
Steps to reproduce:
mount up, press forward key, try using right mouse button to control the camera.
Results:
camera ends up under my raptors tail, real fast
Expected results:
camera rotates to desired location

Is there an environment variable to disable raw input and use staging input instead?

**Comment by Kron4ek** [comment]
Thanks for the report.

> Is there an environment variable to disable raw input and use staging input instead?

Unfortunately no, it can not be disabled using an env variable. Use 5.0-rc1 for now as a temporary solution.

By the way, similar Raw Input patches have [arrived](https://github.com/wine-staging/wine-staging/commit/8218a789558bf074bd26a9adf3bbf05bdb9cb88e) into the Staging patchset recently and they will be included into the Staging 5.0-rc3 release, so there is a chance that it will have the same problem.

You can try GW2 on Proton 4.11-11 (as it includes Raw Input too) to see if the same camera problem is present there, and if so, then it's better to report to Proton's github repo, maybe they fix this problem.

Considering this, perhaps i will disable Raw Input patchset in my 5.0-rc3 improved build.

**Comment by Mel34** [comment]
Unfortunaty arch is also on wine 5.0rc2 so anything lower than that prevents the games from running. Version missmatch bug. Thanks for letting me know!

**Comment by Kron4ek** [comment]
Could you please try [this](https://drive.google.com/open?id=1iiVRqRJi1MaWtQwiN9RUqA_xlsCNb-mF) and [this](https://drive.google.com/open?id=1WIoVwOb14i9I9jUQ_mT_89VAVsUZVzeJ) builds, does the problem with camera happens on them?

**Comment by Mel34** [comment]
Sorry for the delay. I tested both builds. Gw2 doesn't start with wine-5.0-rc2-git-staging-amd64 and has the same issue with mouse with wine-5.0-rc2-staging-impr ... awinput-test-amd64.

**Comment by Kron4ek** [comment]
Ok. So there is no the mouse problem with the 5.0-rc1 improved build, right?

**Comment by Mel34** [comment]
Yes, it's fine in rc1.

**Comment by Kron4ek** [comment]
Ok, thanks.

I wonder if the Staging's Raw Input patchset that will be included in 5.0-rc3 will have the same problem. Please also try the Staging (not improved) 5.0-rc3 when it will be released, and let me know if there will be the same mouse problem on it.

**Comment by Mel34** [comment]
Will do. Thanks.

**Comment by Mel34** [comment]
Reporting back my findings:
Improved staging rc3 has the same mouse issue.
Staging (not improved) rc3 doesn't even launch the game.
And the special file you provided without raw input works great. Many thanks for making that one.
