### ISSUE TITLE
Naming convention helping automation

### ISSUE THREAD

**Issue by koplo199** [Kron4ek/Wine-Builds#91]
Hi :wave: 
Thank you for providing these builds. As you may know, they are included in the official [runners list ](https://github.com/bottlesdevs/components/blob/99e3f51feda9dfb1873bcf116cae4b80efa64ec2/index.yml#L673)in [Bottles](https://github.com/bottlesdevs/Bottles). 

We're currently in the process of automating the update process, and got a [working workflow](https://github.com/bottlesdevs/components/blob/d6c55777c9f17cbdc3c30e47f9d9a32f03e2391a/.github/workflows/pull-components.yml#L53-L58) for your regular `wine` builds !

However, currently it is near impossible for us to also support your `wine-proton` builds. What would greatly help is a small change in the naming convention for these particular builds: from `VERSION-proton` to `proton-VERSION`.

For instance,
Tag name: [7.0-6-proton](https://github.com/Kron4ek/Wine-Builds/releases/tag/7.0-6-proton) -> [proton-7.0-6](https://github.com/Kron4ek/Wine-Builds/releases/tag/proton-7.0-6) 
Asset(s) name(s): [wine-7.0-6-proton-amd64.tar.xz](https://github.com/Kron4ek/Wine-Builds/releases/download/7.0-6-proton/wine-7.0-6-proton-amd64.tar.xz) -> [wine-proton-7.0-6-amd64.tar.xz](https://github.com/Kron4ek/Wine-Builds/releases/download/7.0-6-proton/wine-7.0-6-proton-amd64.tar.xz)

If that is something you could consider doing for _future_ releases, please let us know. In that case it would be very quick to add support for these builds as well.

Thank you for your time.

**Comment by Kron4ek** [comment]
> If that is something you could consider doing for future releases, please let us know. In that case it would be very quick to add support for these builds as well.

Sure, will do that for future releases.

**Comment by koplo199** [comment]
As the issue has been settled, I'm closing it to keep the issue tracker clean. Thanks again @Kron4ek.
