### ISSUE TITLE
Wine stable 8.0.1 ?

### ISSUE THREAD

**Issue by ThieuMinh26** [Kron4ek/Wine-Builds#94]
Hi, can you release wine 8.0.1 build ?
https://www.winehq.org/announce/8.0.1

**Comment by Kron4ek** [comment]
[Uploaded](https://mega.nz/folder/ZZUV1K7J#kIenmTQoi0if-SAcMSuAHA).

**Comment by Kron4ek** [comment]
I do not upload stable builds to github.

**Comment by Kron4ek** [comment]
Though maybe it's a good idea to start uploading them to github too. I uploaded 8.0.1 to github.
