### ISSUE TITLE
VirusTotal has 12 detects

### ISSUE THREAD

**Issue by Ilya114** [Kron4ek/Wine-Builds#95]
![зображення](https://user-images.githubusercontent.com/93242944/234784712-618883cf-0d32-495a-b6f3-c7f20de66b9f.png)
I would like to know why VirusTotal detects your Wine builds as viruses

**Comment by Kron4ek** [comment]
False detections, i guess. It detects viruses in the official Proton 8.0 build from Steam too. 

1. Download Proton 8.0 from Steam
2. Compress its lib (or lib64) to tar.xz
3. Upload lib.tar.xz to VirusTotal and you will see this:

![proton_virustotal](https://user-images.githubusercontent.com/13851877/234791421-bbdb6ba1-12ad-4feb-bccc-64356414dbb3.png)

Which, obviously, does not mean there are viruses.

**Comment by Ilya114** [comment]
![зображення](https://user-images.githubusercontent.com/93242944/234793390-cfe73b73-bd26-4103-86fd-45f45f98a874.png)
Just Wine has only 4 detects, there is a false too?

**Comment by Kron4ek** [comment]
> Just Wine has only 4 detects, there is a false too?

Most likely. I compile all my builds from original source in a clean virtual environment, so there is zero chance of malicious code present, unless it is present in the source code or in the compiler, which is unlikely.

As i said, it detects viruses even in the official Proton 8.0 build, I wouldn't take these detections seriously.
