### ISSUE TITLE
wine-8.7-staging-tkg-amd64

### ISSUE THREAD

**Issue by mksaleem** [Kron4ek/Wine-Builds#96]
Hi,

Thank you for wine 8.7 update
I am having some problem running wow using [wine-8.7-staging-tkg-amd64.tar.xz] but it runs fine using [wine-8.7-staging-amd64.tar.xz]
Following is the error in the log file:
wineserver: using server-side synchronization.
[0513/204008.037:ERROR:network_change_notifier_win.cc(142)] WSALookupServiceBegin failed with: 0
[0513/204008.251:ERROR:network_change_notifier_win.cc(142)] WSALookupServiceBegin failed with: 0
[0513/204008.254:ERROR:dxva_video_decode_accelerator_win.cc(1405)] DXVAVDA fatal error: could not LoadLibrary: msvproc.dll: Module not found. (0x7E)
Initial process has exited (return code: 256)
Monitored process exited.
Exit with return code 256

Update 15/05/23:
Tried wine-8.8-staging-tkg-amd64.tar.xz with the same issue as 8.7

Kind Regards

**Comment by Kron4ek** [comment]
Hi,

Is it latest World of Warcraft from Battle Net, or some older version?

**Comment by mksaleem** [comment]
It is latest World of Warcraft
I didnt check Does it work with staging-tkg 8.6, but working perfectly fine with Does it work with staging-tkg 8.5
I will try 8.6, thanks :)

**Comment by mksaleem** [comment]
wine-8.10-staging-tkg-amd64
fsync: up and running.
[0616/220913.118:ERROR:network_change_notifier_win.cc(142)] WSALookupServiceBegin failed with: 0
[0616/220913.324:ERROR:network_change_notifier_win.cc(142)] WSALookupServiceBegin failed with: 0
[0616/220913.346:ERROR:dxva_video_decode_accelerator_win.cc(1405)] DXVAVDA fatal error: could not LoadLibrary: msvproc.dll: Module not found. (0x7E)
Initial process has exited (return code: 256)

**Comment by Etaash-mathamsetty** [comment]
> Hi,
> 
> Is this latest World of Warcraft from Battle Net, or some older version (like 3.3.5a)? Does it work with staging-tkg 8.6?
> 
> Edit. Ok, i tried to run Battle Net with staging-tkg 8.7 and can't even install it, it crashes at the installation. But it works with staging-tkg 8.6, which means this is a regression in staging-tkg 8.7. Don't know how to fix it though, so i suggest you to use staging-tkg 8.6 or staging 8.7 for now.

I think it's something do you with the way you are building it or patches that you have added, I built a default wine-tkg-git on my system and it works fine :/

**Comment by Kron4ek** [comment]
The thing is there is no difference in patches and building process between 8.6-staging-tkg and 8.7-staging-tkg (except for proton-vr which i doubt has anything to do with this), and nonetheless BattleNet does not work with the latter (and newer versions). It's a regression in some of the already used patches, i think.

**Comment by Kron4ek** [comment]
Ok, will try to build with `_protonify` disabled next time.

> proton-win10-default.patch -- ( Enforce win10 as default wine version ) is not needed (wine 8.3+ use windows 10 as the default version)

It does, but it reports older Windows 10 build than required for some games, so it is still useful (https://github.com/Frogging-Family/wine-tkg-git/commit/3d3535b1a3a4ae29b9353e45ddf1d043ff65f50d).

**Comment by Etaash-mathamsetty** [comment]
> Ok, will try to build with `_protonify` disabled next time.
> 
> > proton-win10-default.patch -- ( Enforce win10 as default wine version ) is not needed (wine 8.3+ use windows 10 as the default version)
> 
> Although Wine sets Windows 10 by default now, it reports older Windows 10 build than required for some games, so the patch is still useful ([Frogging-Family/wine-tkg-git@3d3535b](https://github.com/Frogging-Family/wine-tkg-git/commit/3d3535b1a3a4ae29b9353e45ddf1d043ff65f50d)).

Upstream reports 18362 build number, this patch is 18683, more or less the same thing, that patch is outdated (wine 8.3 also has a Windows 11 mode that reports 22000 I think)

**Comment by Kron4ek** [comment]
This is 19043, not 18363.

**Comment by Etaash-mathamsetty** [comment]
> This patch reports 19043, not 18683.

it's still the old number in kernel32's resource file, but I should have read the commit's message mb

**Comment by Etaash-mathamsetty** [comment]
Works perfect now, thanks so much!

**Comment by Kron4ek** [comment]
Works for me too now, so `_protonify` was the issue indeed.

@mksaleem Try 8.11-staging-tkg.

**Comment by mksaleem** [comment]
Works perfectly now, thanks for sorting it out.
