### ISSUE TITLE
Feature Request: New WoW64 for mainline and staging builds (for 8.10+)

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [Kron4ek/Wine-Builds#98]
When wine 8.10 releases, is it possible for you to compile the new style wow64 builds (that don't require 32 bit deps on the host system)? Mainline works fine, but staging needs a patch disabled (ntdll-Syscall_Emulation), I'm unsure what other patches need to be disabled for the tkg patches to work with the new WoW64, so that's why staging and mainline together should be fine for now.

**Comment by Kron4ek** [comment]
I don't know if they are worth adding to the releases page as they are still experimental, but I can add them to [Actions](https://github.com/Kron4ek/Wine-Builds/actions) so that they are automatically compiled every two weeks, i can do that even before 8.10 release.

**Comment by Kron4ek** [comment]
https://github.com/Kron4ek/Wine-Builds/actions/workflows/wine-exp-wow64.yml

**Comment by gabriele2000** [comment]
> When wine 8.10 releases, is it possible for you to compile the new style wow64 builds (that don't require 32 bit deps on the host system)? Mainline works fine, but staging needs a patch disabled (ntdll-Syscall_Emulation), I'm unsure what other patches need to be disabled for the tkg patches to work with the new WoW64, so that's why staging and mainline together should be fine for now.

Is that why the 32-bit libs gets built even if I disabled the 32-bit lib building?

**Comment by Kron4ek** [comment]
@xDoge26 https://github.com/Kron4ek/Wine-Builds/actions/workflows/wine-exp-wow64.yml
