### ISSUE TITLE
Problem installing and running

### ISSUE THREAD

**Issue by ubanning** [Kron4ek/Wine-Builds#99]
Hello, I'm getting several issues installing Wine.

I'm trying to use wine-8.0.1-amd64 together with Box64, but the problem is occurring with any version.

Following the tutorial of just downloading and extracting and running, as in the example you provided:
`/home/username/wine-7.0-amd64/bin/wine application.exe`
Getting the error:
`/home/ubuntu/wine-8.0.1-amd64/bin/wine: cannot execute binary file: Exec format error`

If I change it to `wine64`, it works! Example:
`/home/ubuntu/wine-8.0.1-amd64/bin/wine64 --version`

But when I run a file, the following error appears:
/home/ubuntu/wine-8.0.1-amd64/bin/wine64 PeEditor.exe
`wine: '/root/.wine' is a 32-bit installation, it cannot support 64-bit applications.`

I've also tried using `create_ubuntu_bootstraps.sh` and `build_wine.sh`, but at the end of the build_wine.sh script, I get the following error:
```
bwrap: Can't mkdir /mnt: Read-only file system
bwrap: Can't mkdir /mnt: Read-only file system
bwrap: Can't mkdir /mnt: Read-only file system
bwrap: Can't mkdir /mnt: Read-only file system
bwrap: Can't mkdir /mnt: Read-only file system
bwrap: Can't mkdir /mnt: Read-only file system
bwrap: Can't mkdir /mnt: Read-only file system
bwrap: Can't mkdir /mnt: Read-only file system
bwrap: Can't mkdir /mnt: Read-only file system
```

I believe the problem is with my machine.
I'm using:
Ubuntu 22.04.2 LTS
aarch64
I'm using an environment without a graphical interface (only terminal), so I can't open winecfg.

Can you help me? Thank you very much!

**Comment by Kron4ek** [comment]
Hello.

> /home/ubuntu/wine-8.0.1-amd64/bin/wine: cannot execute binary file: Exec format error

`wine` is a 32-bit binary (x86), `wine64` is a 64-bit binary (x86-64). Seems like Box64 can't run 32-bit binaries.

> wine: '/root/.wine' is a 32-bit installation, it cannot support 64-bit applications.

Remove or rename your `/root/.wine` directory and Wine will create a new prefix.

**Comment by ubanning** [comment]
Hello, thanks for the reply :)
> wine is a 32-bit binary (x86), wine64 is a 64-bit binary (x86-64). Seems like Box64 can't run 32-bit binaries. 

Now I understand why I can't open it, thanks, but since the file I want to open is a 64-bit file, I'll have to use wine64 anyway. Therefore, the problem must not be related to this, since I was already using the correct wine

> Remove or rename your /root/.wine directory and Wine will create a new prefix. However, if PeEditor.exe is a 32-bit application, you won't be able to run it with Box64 + wine64, you will need to use Box86 + wine x86.

There is no directory called .wine in /root. The only directory that exists in /root on my machine is `snap`
About the application, it is 64bit, and that's why I'm finding this error strange: `wine: '/root/.wine' is a 32-bit installation, it cannot support 64-bit applications`. Since I'm using wine64, I don't know why the error is talking about 32-bit, as seen earlier I'm not even able to start 32-bit wine because I only have Box64.

**Comment by Kron4ek** [comment]
> There is no directory called .wine in /root.

Are you sure? Its name starts with dot, so it's a hidden directory. You can check if it exists or now with this command:

```
ls -l /root/.wine
```

**Comment by ubanning** [comment]
It really was there, but it was hidden like you said! 
Now it worked perfectly!! Thanks a lot for the help. :) :)
